// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DeployParamsInitParameters struct {

	// The distro series used to deploy the specifed MAAS machine. If it's not given, the MAAS server default value is used.
	DistroSeries *string `json:"distroSeries,omitempty" tf:"distro_series,omitempty"`

	// Periodically sync hardware
	EnableHwSync *bool `json:"enableHwSync,omitempty" tf:"enable_hw_sync,omitempty"`

	// Hardware enablement kernel to use with the image. Only used when deploying Ubuntu.
	HweKernel *string `json:"hweKernel,omitempty" tf:"hwe_kernel,omitempty"`

	// Cloud-init user data script that gets run on the machine once it has deployed. A good practice is to set this with `file("/tmp/user-data.txt")`, where `/tmp/user-data.txt` is a cloud-init script.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type DeployParamsObservation struct {

	// The distro series used to deploy the specifed MAAS machine. If it's not given, the MAAS server default value is used.
	DistroSeries *string `json:"distroSeries,omitempty" tf:"distro_series,omitempty"`

	// Periodically sync hardware
	EnableHwSync *bool `json:"enableHwSync,omitempty" tf:"enable_hw_sync,omitempty"`

	// Hardware enablement kernel to use with the image. Only used when deploying Ubuntu.
	HweKernel *string `json:"hweKernel,omitempty" tf:"hwe_kernel,omitempty"`

	// Cloud-init user data script that gets run on the machine once it has deployed. A good practice is to set this with `file("/tmp/user-data.txt")`, where `/tmp/user-data.txt` is a cloud-init script.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type DeployParamsParameters struct {

	// The distro series used to deploy the specifed MAAS machine. If it's not given, the MAAS server default value is used.
	// +kubebuilder:validation:Optional
	DistroSeries *string `json:"distroSeries,omitempty" tf:"distro_series,omitempty"`

	// Periodically sync hardware
	// +kubebuilder:validation:Optional
	EnableHwSync *bool `json:"enableHwSync,omitempty" tf:"enable_hw_sync,omitempty"`

	// Hardware enablement kernel to use with the image. Only used when deploying Ubuntu.
	// +kubebuilder:validation:Optional
	HweKernel *string `json:"hweKernel,omitempty" tf:"hwe_kernel,omitempty"`

	// Cloud-init user data script that gets run on the machine once it has deployed. A good practice is to set this with `file("/tmp/user-data.txt")`, where `/tmp/user-data.txt` is a cloud-init script.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type VMHostInitParameters struct {

	// (Number) The new VM host CPU overcommit ratio. This is computed if it's not set.
	// The new VM host CPU overcommit ratio. This is computed if it's not set.
	CPUOverCommitRatio *float64 `json:"cpuOverCommitRatio,omitempty" tf:"cpu_over_commit_ratio,omitempty"`

	// Certificate to use for power control of a LXD VM host. It can't be set if `machine`, `power_user` or `power_pass` parameters are used.
	CertificateSecretRef *v1.LocalSecretKeySelector `json:"certificateSecretRef,omitempty" tf:"-"`

	// (String) The new VM host default macvlan mode. Supported values are: bridge, passthru, private, vepa. This is computed if it's not set.
	// The new VM host default macvlan mode. Supported values are: `bridge`, `passthru`, `private`, `vepa`. This is computed if it's not set.
	DefaultMacvlanMode *string `json:"defaultMacvlanMode,omitempty" tf:"default_macvlan_mode,omitempty"`

	// Nested argument with the config used to deploy the machine specified using `machine`.
	DeployParams []DeployParamsInitParameters `json:"deployParams,omitempty" tf:"deploy_params,omitempty"`

	// Certificate key to use for power control of a LXD VM host. It can't be set if `machine`, `power_user`, or `power_pass` parameters are used.
	KeySecretRef *v1.LocalSecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// (String) The identifier (hostname, FQDN or system ID) of a registered ready MAAS machine. This is going to be deployed and registered as a new VM host. This argument conflicts with: power_address, power_user, power_pass.
	// The identifier (hostname, FQDN or system ID) of a registered ready MAAS machine. This is going to be deployed and registered as a new VM host. This argument conflicts with: `power_address`, `power_user`, `power_pass`, `certificate`, `key` and `password`.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The new VM host RAM memory overcommit ratio. This is computed if it's not set.
	// The new VM host RAM memory overcommit ratio. This is computed if it's not set.
	MemoryOverCommitRatio *float64 `json:"memoryOverCommitRatio,omitempty" tf:"memory_over_commit_ratio,omitempty"`

	// (String) The new VM host name. This is computed if it's not set.
	// The new VM host name. This is computed if it's not set.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// LXD trust password to use for power control of a LXD VM Host. If parameters `certificate` and `key` are used, the trust password will be used to trust the certificate-key pair. If no `certificate` and `key` are specified, MAAS will generate a trusted certificate and key for the VM host. It can't be set if `machine`, `power_user`, or `power_pass` parameters are used.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) The new VM host pool name. This is computed if it's not set.
	// The new VM host pool name. This is computed if it's not set.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/infrastructure/v1alpha1.ResourcePool
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v1.NamespacedReference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v1.NamespacedSelector `json:"poolSelector,omitempty" tf:"-"`

	// (String) Address that gives MAAS access to the VM host power control. For example: qemu+ssh://172.16.99.2/system. The address given here must reachable by the MAAS server. It can't be set if machine argument is used.
	// Address that gives MAAS access to the VM host power control. For example: `qemu+ssh://172.16.99.2/system`. The address given here must reachable by the MAAS server. It can't be set if `machine` argument is used.
	PowerAddress *string `json:"powerAddress,omitempty" tf:"power_address,omitempty"`

	// (String, Sensitive) User password to use for power control of the VM host. Cannot be set if machine parameter is used.
	// User password to use for power control of a Virsh VM host. Cannot be set if `machine`, `certificate`, `key` or `password` parameters are used.
	PowerPassSecretRef *v1.LocalSecretKeySelector `json:"powerPassSecretRef,omitempty" tf:"-"`

	// (String) User name to use for power control of the VM host. Cannot be set if machine parameter is used.
	// User name to use for power control of a Virsh VM host. Cannot be set if `machine`, `certificate`, `key` or `password` parameters are used.
	PowerUser *string `json:"powerUser,omitempty" tf:"power_user,omitempty"`

	// LXD project to be used by VM host to deploy machines to. Cannot be set if `machine`, `power_user` or `power_pass` parameters are used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// (Set of String) A set of tag names to assign to the new VM host. This is computed if it's not set.
	// A set of tag names to assign to the new VM host. This is computed if it's not set.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The VM host type. Supported values are: lxd, virsh.
	// The VM host type. Supported values are: `lxd`, `virsh`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The new VM host zone name. This is computed if it's not set.
	// The new VM host zone name. This is computed if it's not set.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VMHostObservation struct {

	// (Number) The new VM host CPU overcommit ratio. This is computed if it's not set.
	// The new VM host CPU overcommit ratio. This is computed if it's not set.
	CPUOverCommitRatio *float64 `json:"cpuOverCommitRatio,omitempty" tf:"cpu_over_commit_ratio,omitempty"`

	// (String) The new VM host default macvlan mode. Supported values are: bridge, passthru, private, vepa. This is computed if it's not set.
	// The new VM host default macvlan mode. Supported values are: `bridge`, `passthru`, `private`, `vepa`. This is computed if it's not set.
	DefaultMacvlanMode *string `json:"defaultMacvlanMode,omitempty" tf:"default_macvlan_mode,omitempty"`

	// Nested argument with the config used to deploy the machine specified using `machine`.
	DeployParams []DeployParamsObservation `json:"deployParams,omitempty" tf:"deploy_params,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The identifier (hostname, FQDN or system ID) of a registered ready MAAS machine. This is going to be deployed and registered as a new VM host. This argument conflicts with: power_address, power_user, power_pass.
	// The identifier (hostname, FQDN or system ID) of a registered ready MAAS machine. This is going to be deployed and registered as a new VM host. This argument conflicts with: `power_address`, `power_user`, `power_pass`, `certificate`, `key` and `password`.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The new VM host RAM memory overcommit ratio. This is computed if it's not set.
	// The new VM host RAM memory overcommit ratio. This is computed if it's not set.
	MemoryOverCommitRatio *float64 `json:"memoryOverCommitRatio,omitempty" tf:"memory_over_commit_ratio,omitempty"`

	// (String) The new VM host name. This is computed if it's not set.
	// The new VM host name. This is computed if it's not set.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The new VM host pool name. This is computed if it's not set.
	// The new VM host pool name. This is computed if it's not set.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// (String) Address that gives MAAS access to the VM host power control. For example: qemu+ssh://172.16.99.2/system. The address given here must reachable by the MAAS server. It can't be set if machine argument is used.
	// Address that gives MAAS access to the VM host power control. For example: `qemu+ssh://172.16.99.2/system`. The address given here must reachable by the MAAS server. It can't be set if `machine` argument is used.
	PowerAddress *string `json:"powerAddress,omitempty" tf:"power_address,omitempty"`

	// (String) User name to use for power control of the VM host. Cannot be set if machine parameter is used.
	// User name to use for power control of a Virsh VM host. Cannot be set if `machine`, `certificate`, `key` or `password` parameters are used.
	PowerUser *string `json:"powerUser,omitempty" tf:"power_user,omitempty"`

	// LXD project to be used by VM host to deploy machines to. Cannot be set if `machine`, `power_user` or `power_pass` parameters are used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// (Number) The VM host total number of CPU cores.
	// The VM host total number of CPU cores.
	ResourcesCoresTotal *float64 `json:"resourcesCoresTotal,omitempty" tf:"resources_cores_total,omitempty"`

	// (Number) The VM host total local storage (in bytes).
	// The VM host total local storage (in bytes).
	ResourcesLocalStorageTotal *float64 `json:"resourcesLocalStorageTotal,omitempty" tf:"resources_local_storage_total,omitempty"`

	// (Number) The VM host total RAM memory (in MB).
	// The VM host total RAM memory (in MB).
	ResourcesMemoryTotal *float64 `json:"resourcesMemoryTotal,omitempty" tf:"resources_memory_total,omitempty"`

	// (Set of String) A set of tag names to assign to the new VM host. This is computed if it's not set.
	// A set of tag names to assign to the new VM host. This is computed if it's not set.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The VM host type. Supported values are: lxd, virsh.
	// The VM host type. Supported values are: `lxd`, `virsh`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The new VM host zone name. This is computed if it's not set.
	// The new VM host zone name. This is computed if it's not set.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VMHostParameters struct {

	// (Number) The new VM host CPU overcommit ratio. This is computed if it's not set.
	// The new VM host CPU overcommit ratio. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	CPUOverCommitRatio *float64 `json:"cpuOverCommitRatio,omitempty" tf:"cpu_over_commit_ratio,omitempty"`

	// Certificate to use for power control of a LXD VM host. It can't be set if `machine`, `power_user` or `power_pass` parameters are used.
	// +kubebuilder:validation:Optional
	CertificateSecretRef *v1.LocalSecretKeySelector `json:"certificateSecretRef,omitempty" tf:"-"`

	// (String) The new VM host default macvlan mode. Supported values are: bridge, passthru, private, vepa. This is computed if it's not set.
	// The new VM host default macvlan mode. Supported values are: `bridge`, `passthru`, `private`, `vepa`. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	DefaultMacvlanMode *string `json:"defaultMacvlanMode,omitempty" tf:"default_macvlan_mode,omitempty"`

	// Nested argument with the config used to deploy the machine specified using `machine`.
	// +kubebuilder:validation:Optional
	DeployParams []DeployParamsParameters `json:"deployParams,omitempty" tf:"deploy_params,omitempty"`

	// Certificate key to use for power control of a LXD VM host. It can't be set if `machine`, `power_user`, or `power_pass` parameters are used.
	// +kubebuilder:validation:Optional
	KeySecretRef *v1.LocalSecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// (String) The identifier (hostname, FQDN or system ID) of a registered ready MAAS machine. This is going to be deployed and registered as a new VM host. This argument conflicts with: power_address, power_user, power_pass.
	// The identifier (hostname, FQDN or system ID) of a registered ready MAAS machine. This is going to be deployed and registered as a new VM host. This argument conflicts with: `power_address`, `power_user`, `power_pass`, `certificate`, `key` and `password`.
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The new VM host RAM memory overcommit ratio. This is computed if it's not set.
	// The new VM host RAM memory overcommit ratio. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	MemoryOverCommitRatio *float64 `json:"memoryOverCommitRatio,omitempty" tf:"memory_over_commit_ratio,omitempty"`

	// (String) The new VM host name. This is computed if it's not set.
	// The new VM host name. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// LXD trust password to use for power control of a LXD VM Host. If parameters `certificate` and `key` are used, the trust password will be used to trust the certificate-key pair. If no `certificate` and `key` are specified, MAAS will generate a trusted certificate and key for the VM host. It can't be set if `machine`, `power_user`, or `power_pass` parameters are used.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) The new VM host pool name. This is computed if it's not set.
	// The new VM host pool name. This is computed if it's not set.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/infrastructure/v1alpha1.ResourcePool
	// +kubebuilder:validation:Optional
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v1.NamespacedReference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v1.NamespacedSelector `json:"poolSelector,omitempty" tf:"-"`

	// (String) Address that gives MAAS access to the VM host power control. For example: qemu+ssh://172.16.99.2/system. The address given here must reachable by the MAAS server. It can't be set if machine argument is used.
	// Address that gives MAAS access to the VM host power control. For example: `qemu+ssh://172.16.99.2/system`. The address given here must reachable by the MAAS server. It can't be set if `machine` argument is used.
	// +kubebuilder:validation:Optional
	PowerAddress *string `json:"powerAddress,omitempty" tf:"power_address,omitempty"`

	// (String, Sensitive) User password to use for power control of the VM host. Cannot be set if machine parameter is used.
	// User password to use for power control of a Virsh VM host. Cannot be set if `machine`, `certificate`, `key` or `password` parameters are used.
	// +kubebuilder:validation:Optional
	PowerPassSecretRef *v1.LocalSecretKeySelector `json:"powerPassSecretRef,omitempty" tf:"-"`

	// (String) User name to use for power control of the VM host. Cannot be set if machine parameter is used.
	// User name to use for power control of a Virsh VM host. Cannot be set if `machine`, `certificate`, `key` or `password` parameters are used.
	// +kubebuilder:validation:Optional
	PowerUser *string `json:"powerUser,omitempty" tf:"power_user,omitempty"`

	// LXD project to be used by VM host to deploy machines to. Cannot be set if `machine`, `power_user` or `power_pass` parameters are used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// (Set of String) A set of tag names to assign to the new VM host. This is computed if it's not set.
	// A set of tag names to assign to the new VM host. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The VM host type. Supported values are: lxd, virsh.
	// The VM host type. Supported values are: `lxd`, `virsh`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The new VM host zone name. This is computed if it's not set.
	// The new VM host zone name. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// VMHostSpec defines the desired state of VMHost
type VMHostSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VMHostParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VMHostInitParameters `json:"initProvider,omitempty"`
}

// VMHostStatus defines the observed state of VMHost.
type VMHostStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VMHostObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VMHost is the Schema for the VMHosts API. Provides a resource to manage MAAS VM hosts.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type VMHost struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   VMHostSpec   `json:"spec"`
	Status VMHostStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VMHostList contains a list of VMHosts
type VMHostList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VMHost `json:"items"`
}

// Repository type metadata.
var (
	VMHost_Kind             = "VMHost"
	VMHost_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VMHost_Kind}.String()
	VMHost_KindAPIVersion   = VMHost_Kind + "." + CRDGroupVersion.String()
	VMHost_GroupVersionKind = CRDGroupVersion.WithKind(VMHost_Kind)
)

func init() {
	SchemeBuilder.Register(&VMHost{}, &VMHostList{})
}
