apiVersion: infrastructure.maas.m.crossplane.io/v1alpha1
kind: ResourcePool
metadata:
  annotations:
    meta.upbound.io/example-id: infrastructure/v1alpha1/resourcepool
  labels:
    testing.upbound.io/example-name: test_resource_pool
  name: test-resource-pool
  namespace: crossplane-system
spec:
  forProvider:
    description: Test description
    name: test-resource-pool
