// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DeviceInitParameters struct {

	// (String) The description of the device.
	// The description of the device.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain of the device.
	// The domain of the device.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The device hostname.
	// The device hostname.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (Block Set, Min: 1) A set of network interfaces attached to the device. (see below for nested schema)
	// A set of network interfaces attached to the device.
	NetworkInterfaces []NetworkInterfacesInitParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (String) The zone of the device.
	// The zone of the device.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DeviceObservation struct {

	// (String) The description of the device.
	// The description of the device.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain of the device.
	// The domain of the device.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The device FQDN.
	// The device FQDN.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// (String) The device hostname.
	// The device hostname.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) A set of IP addressed assigned to the device.
	// A set of IP addressed assigned to the device.
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// (Block Set, Min: 1) A set of network interfaces attached to the device. (see below for nested schema)
	// A set of network interfaces attached to the device.
	NetworkInterfaces []NetworkInterfacesObservation `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (String) The owner of the device.
	// The owner of the device.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String) The zone of the device.
	// The zone of the device.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DeviceParameters struct {

	// (String) The description of the device.
	// The description of the device.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain of the device.
	// The domain of the device.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The device hostname.
	// The device hostname.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (Block Set, Min: 1) A set of network interfaces attached to the device. (see below for nested schema)
	// A set of network interfaces attached to the device.
	// +kubebuilder:validation:Optional
	NetworkInterfaces []NetworkInterfacesParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (String) The zone of the device.
	// The zone of the device.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NetworkInterfacesInitParameters struct {

	// (String) MAC address of the network interface.
	// MAC address of the network interface.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`
}

type NetworkInterfacesObservation struct {

	// (String) The ID of this resource.
	// The id of the network interface.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// (String) MAC address of the network interface.
	// MAC address of the network interface.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The name of the network interface.
	// The name of the network interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type NetworkInterfacesParameters struct {

	// (String) MAC address of the network interface.
	// MAC address of the network interface.
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress" tf:"mac_address,omitempty"`
}

// DeviceSpec defines the desired state of Device
type DeviceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DeviceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeviceInitParameters `json:"initProvider,omitempty"`
}

// DeviceStatus defines the observed state of Device.
type DeviceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeviceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Device is the Schema for the Devices API. Provides a resource to manage MAAS devices.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type Device struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkInterfaces) || (has(self.initProvider) && has(self.initProvider.networkInterfaces))",message="spec.forProvider.networkInterfaces is a required parameter"
	Spec   DeviceSpec   `json:"spec"`
	Status DeviceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeviceList contains a list of Devices
type DeviceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Device `json:"items"`
}

// Repository type metadata.
var (
	Device_Kind             = "Device"
	Device_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Device_Kind}.String()
	Device_KindAPIVersion   = Device_Kind + "." + CRDGroupVersion.String()
	Device_GroupVersionKind = CRDGroupVersion.WithKind(Device_Kind)
)

func init() {
	SchemeBuilder.Register(&Device{}, &DeviceList{})
}
