// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TagInitParameters struct {

	// (String) A description of what the the tag will be used for in natural language.
	// A description of what the the tag will be used for in natural language.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// xml)
	// An XPATH query that is evaluated against the hardware_details stored for all nodes. (i.e. the output of “lshw -xml“)
	Definition *string `json:"definition,omitempty" tf:"definition,omitempty"`

	// (String) Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global kernel_opts setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.
	// Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global “kernel_opts“ setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.
	KernelOpts *string `json:"kernelOpts,omitempty" tf:"kernel_opts,omitempty"`

	// (Set of String) List of MAAS machines' identifiers (system ID, hostname, or FQDN) that will be tagged with the new tag.
	// List of MAAS machines' identifiers (system ID, hostname, or FQDN) that will be tagged with the new tag.
	// +listType=set
	Machines []*string `json:"machines,omitempty" tf:"machines,omitempty"`

	// (String) The new tag name. Because the name will be used in urls, it should be short.
	// The new tag name. Because the name will be used in urls, it should be short.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TagObservation struct {

	// (String) A description of what the the tag will be used for in natural language.
	// A description of what the the tag will be used for in natural language.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// xml)
	// An XPATH query that is evaluated against the hardware_details stored for all nodes. (i.e. the output of “lshw -xml“)
	Definition *string `json:"definition,omitempty" tf:"definition,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global kernel_opts setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.
	// Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global “kernel_opts“ setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.
	KernelOpts *string `json:"kernelOpts,omitempty" tf:"kernel_opts,omitempty"`

	// (Set of String) List of MAAS machines' identifiers (system ID, hostname, or FQDN) that will be tagged with the new tag.
	// List of MAAS machines' identifiers (system ID, hostname, or FQDN) that will be tagged with the new tag.
	// +listType=set
	Machines []*string `json:"machines,omitempty" tf:"machines,omitempty"`

	// (String) The new tag name. Because the name will be used in urls, it should be short.
	// The new tag name. Because the name will be used in urls, it should be short.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TagParameters struct {

	// (String) A description of what the the tag will be used for in natural language.
	// A description of what the the tag will be used for in natural language.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// xml)
	// An XPATH query that is evaluated against the hardware_details stored for all nodes. (i.e. the output of “lshw -xml“)
	// +kubebuilder:validation:Optional
	Definition *string `json:"definition,omitempty" tf:"definition,omitempty"`

	// (String) Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global kernel_opts setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.
	// Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global “kernel_opts“ setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.
	// +kubebuilder:validation:Optional
	KernelOpts *string `json:"kernelOpts,omitempty" tf:"kernel_opts,omitempty"`

	// (Set of String) List of MAAS machines' identifiers (system ID, hostname, or FQDN) that will be tagged with the new tag.
	// List of MAAS machines' identifiers (system ID, hostname, or FQDN) that will be tagged with the new tag.
	// +kubebuilder:validation:Optional
	// +listType=set
	Machines []*string `json:"machines,omitempty" tf:"machines,omitempty"`

	// (String) The new tag name. Because the name will be used in urls, it should be short.
	// The new tag name. Because the name will be used in urls, it should be short.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// TagSpec defines the desired state of Tag
type TagSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TagParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TagInitParameters `json:"initProvider,omitempty"`
}

// TagStatus defines the observed state of Tag.
type TagStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TagObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Tag is the Schema for the Tags API. Provides a resource to manage a MAAS tag, used to tag machines.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,maas}
type Tag struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TagSpec   `json:"spec"`
	Status TagStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TagList contains a list of Tags
type TagList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Tag `json:"items"`
}

// Repository type metadata.
var (
	Tag_Kind             = "Tag"
	Tag_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Tag_Kind}.String()
	Tag_KindAPIVersion   = Tag_Kind + "." + CRDGroupVersion.String()
	Tag_GroupVersionKind = CRDGroupVersion.WithKind(Tag_Kind)
)

func init() {
	SchemeBuilder.Register(&Tag{}, &TagList{})
}
