name: Bug report
description: Report a bug to help us improve provider-upjet-maas
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        **Please do not post secrets** (MAAS API keys, kubeconfigs, tokens).

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Apply ...
        2. Create ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: manifests
    attributes:
      label: Relevant manifests / configs
      description: Paste YAML (redact secrets). Prefer minimal reproducer.
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Provider/controller logs, Crossplane events, etc. (redact secrets).
      render: shell

  - type: input
    id: provider-version
    attributes:
      label: Provider version
      placeholder: e.g. v0.1.0 / ghcr.io/...:tag

  - type: input
    id: crossplane-version
    attributes:
      label: Crossplane version
      placeholder: e.g. v1.16.0

  - type: input
    id: kubernetes-version
    attributes:
      label: Kubernetes version
      placeholder: e.g. v1.30.0

  - type: input
    id: maas-version
    attributes:
      label: MAAS version
      placeholder: e.g. 3.5
