name: Feature request
description: Suggest an idea for provider-upjet-maas
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion!

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I want to be able to ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: We could add ...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What else did you consider?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, related issues/PRs.
