// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/Marouan-chak/provider-upjet-maas/apis/cluster/infrastructure/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Machine.
func (mg *Machine) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Pool),
		Extract:      resource.ExtractParamPath("name", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PoolRef,
		Selector:     mg.Spec.ForProvider.PoolSelector,
		To: reference.To{
			List:    &v1alpha1.ResourcePoolList{},
			Managed: &v1alpha1.ResourcePool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Pool")
	}
	mg.Spec.ForProvider.Pool = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PoolRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Pool),
		Extract:      resource.ExtractParamPath("name", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PoolRef,
		Selector:     mg.Spec.InitProvider.PoolSelector,
		To: reference.To{
			List:    &v1alpha1.ResourcePoolList{},
			Managed: &v1alpha1.ResourcePool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Pool")
	}
	mg.Spec.InitProvider.Pool = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PoolRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this VMHost.
func (mg *VMHost) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Pool),
		Extract:      resource.ExtractParamPath("name", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PoolRef,
		Selector:     mg.Spec.ForProvider.PoolSelector,
		To: reference.To{
			List:    &v1alpha1.ResourcePoolList{},
			Managed: &v1alpha1.ResourcePool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Pool")
	}
	mg.Spec.ForProvider.Pool = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PoolRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Pool),
		Extract:      resource.ExtractParamPath("name", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PoolRef,
		Selector:     mg.Spec.InitProvider.PoolSelector,
		To: reference.To{
			List:    &v1alpha1.ResourcePoolList{},
			Managed: &v1alpha1.ResourcePool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Pool")
	}
	mg.Spec.InitProvider.Pool = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PoolRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this VMHostMachine.
func (mg *VMHostMachine) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VMHost),
		Extract:      resource.ExtractParamPath("name", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VMHostRef,
		Selector:     mg.Spec.ForProvider.VMHostSelector,
		To: reference.To{
			List:    &VMHostList{},
			Managed: &VMHost{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VMHost")
	}
	mg.Spec.ForProvider.VMHost = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VMHostRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VMHost),
		Extract:      resource.ExtractParamPath("name", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VMHostRef,
		Selector:     mg.Spec.InitProvider.VMHostSelector,
		To: reference.To{
			List:    &VMHostList{},
			Managed: &VMHost{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VMHost")
	}
	mg.Spec.InitProvider.VMHost = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VMHostRef = rsp.ResolvedReference

	return nil
}
