// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BlockDevicesInitParameters struct {
}

type BlockDevicesObservation struct {

	// (String)
	IDPath *string `json:"idPath,omitempty" tf:"id_path,omitempty"`

	// (String)
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`
}

type BlockDevicesParameters struct {
}

type MachineInitParameters struct {

	// (String) The architecture type of the machine. Defaults to amd64/generic.
	// The architecture type of the machine. Defaults to `amd64/generic`.
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// (String) The domain of the machine. This is computed if it's not set.
	// The domain of the machine. This is computed if it's not set.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The machine hostname. This is computed if it's not set.
	// The machine hostname. This is computed if it's not set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The minimum kernel version allowed to run on this machine. Only used when deploying Ubuntu. This is computed if it's not set.
	// The minimum kernel version allowed to run on this machine. Only used when deploying Ubuntu. This is computed if it's not set.
	MinHweKernel *string `json:"minHweKernel,omitempty" tf:"min_hwe_kernel,omitempty"`

	// (String) The resource pool of the machine. This is computed if it's not set.
	// The resource pool of the machine. This is computed if it's not set.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/infrastructure/v1alpha1.ResourcePool
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name", true)
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v1.Reference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v1.Selector `json:"poolSelector,omitempty" tf:"-"`

	// (String, Sensitive) Serialized JSON string containing the parameters specific to the power_type. See Power types section for a list of the available power parameters for each power type.
	// Serialized JSON string containing the parameters specific to the `power_type`. See [Power types](https://maas.io/docs/api#power-types) section for a list of the available power parameters for each power type.
	PowerParametersSecretRef v1.SecretKeySelector `json:"powerParametersSecretRef" tf:"-"`

	// (String) A power management type (e.g. ipmi).
	// A power management type (e.g. `ipmi`).
	PowerType *string `json:"powerType,omitempty" tf:"power_type,omitempty"`

	// (String) The MAC address of the machine's PXE boot NIC.
	// The MAC address of the machine's PXE boot NIC.
	PxeMacAddress *string `json:"pxeMacAddress,omitempty" tf:"pxe_mac_address,omitempty"`

	// (String) The zone of the machine. This is computed if it's not set.
	// The zone of the machine. This is computed if it's not set.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type MachineObservation struct {

	// (String) The architecture type of the machine. Defaults to amd64/generic.
	// The architecture type of the machine. Defaults to `amd64/generic`.
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// (List of Object) A list of block devices attached to the machine. (see below for nested schema)
	// A list of block devices attached to the machine.
	BlockDevices []BlockDevicesObservation `json:"blockDevices,omitempty" tf:"block_devices,omitempty"`

	// (String) The domain of the machine. This is computed if it's not set.
	// The domain of the machine. This is computed if it's not set.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The machine hostname. This is computed if it's not set.
	// The machine hostname. This is computed if it's not set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The minimum kernel version allowed to run on this machine. Only used when deploying Ubuntu. This is computed if it's not set.
	// The minimum kernel version allowed to run on this machine. Only used when deploying Ubuntu. This is computed if it's not set.
	MinHweKernel *string `json:"minHweKernel,omitempty" tf:"min_hwe_kernel,omitempty"`

	// (Set of String) A set of MAC addresses of network interfaces attached to the machine.
	// A set of MAC addresses of network interfaces attached to the machine.
	// +listType=set
	NetworkInterfaces []*string `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (String) The resource pool of the machine. This is computed if it's not set.
	// The resource pool of the machine. This is computed if it's not set.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// (String) A power management type (e.g. ipmi).
	// A power management type (e.g. `ipmi`).
	PowerType *string `json:"powerType,omitempty" tf:"power_type,omitempty"`

	// (String) The MAC address of the machine's PXE boot NIC.
	// The MAC address of the machine's PXE boot NIC.
	PxeMacAddress *string `json:"pxeMacAddress,omitempty" tf:"pxe_mac_address,omitempty"`

	// (String) The zone of the machine. This is computed if it's not set.
	// The zone of the machine. This is computed if it's not set.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type MachineParameters struct {

	// (String) The architecture type of the machine. Defaults to amd64/generic.
	// The architecture type of the machine. Defaults to `amd64/generic`.
	// +kubebuilder:validation:Optional
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// (String) The domain of the machine. This is computed if it's not set.
	// The domain of the machine. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The machine hostname. This is computed if it's not set.
	// The machine hostname. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The minimum kernel version allowed to run on this machine. Only used when deploying Ubuntu. This is computed if it's not set.
	// The minimum kernel version allowed to run on this machine. Only used when deploying Ubuntu. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	MinHweKernel *string `json:"minHweKernel,omitempty" tf:"min_hwe_kernel,omitempty"`

	// (String) The resource pool of the machine. This is computed if it's not set.
	// The resource pool of the machine. This is computed if it's not set.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/infrastructure/v1alpha1.ResourcePool
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name", true)
	// +kubebuilder:validation:Optional
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v1.Reference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a ResourcePool in infrastructure to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v1.Selector `json:"poolSelector,omitempty" tf:"-"`

	// (String, Sensitive) Serialized JSON string containing the parameters specific to the power_type. See Power types section for a list of the available power parameters for each power type.
	// Serialized JSON string containing the parameters specific to the `power_type`. See [Power types](https://maas.io/docs/api#power-types) section for a list of the available power parameters for each power type.
	// +kubebuilder:validation:Optional
	PowerParametersSecretRef v1.SecretKeySelector `json:"powerParametersSecretRef" tf:"-"`

	// (String) A power management type (e.g. ipmi).
	// A power management type (e.g. `ipmi`).
	// +kubebuilder:validation:Optional
	PowerType *string `json:"powerType,omitempty" tf:"power_type,omitempty"`

	// (String) The MAC address of the machine's PXE boot NIC.
	// The MAC address of the machine's PXE boot NIC.
	// +kubebuilder:validation:Optional
	PxeMacAddress *string `json:"pxeMacAddress,omitempty" tf:"pxe_mac_address,omitempty"`

	// (String) The zone of the machine. This is computed if it's not set.
	// The zone of the machine. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// MachineSpec defines the desired state of Machine
type MachineSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MachineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MachineInitParameters `json:"initProvider,omitempty"`
}

// MachineStatus defines the observed state of Machine.
type MachineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MachineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Machine is the Schema for the Machines API. Provides a resource to manage MAAS machines.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,maas}
type Machine struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.powerParametersSecretRef)",message="spec.forProvider.powerParametersSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.powerType) || (has(self.initProvider) && has(self.initProvider.powerType))",message="spec.forProvider.powerType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pxeMacAddress) || (has(self.initProvider) && has(self.initProvider.pxeMacAddress))",message="spec.forProvider.pxeMacAddress is a required parameter"
	Spec   MachineSpec   `json:"spec"`
	Status MachineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MachineList contains a list of Machines
type MachineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Machine `json:"items"`
}

// Repository type metadata.
var (
	Machine_Kind             = "Machine"
	Machine_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Machine_Kind}.String()
	Machine_KindAPIVersion   = Machine_Kind + "." + CRDGroupVersion.String()
	Machine_GroupVersionKind = CRDGroupVersion.WithKind(Machine_Kind)
)

func init() {
	SchemeBuilder.Register(&Machine{}, &MachineList{})
}
