// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type NetworkInterfacesInitParameters struct {

	// (String) The fabric for the network interface.
	// The fabric for the network interface.
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) Static IP configured on the new network interface.
	// Static IP configured on the new network interface.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The network interface name.
	// The network interface name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The subnet CIDR for the network interface.
	// The subnet CIDR for the network interface.
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// (String) The VLAN for the network interface.
	// The VLAN for the network interface.
	Vlan *string `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type NetworkInterfacesObservation struct {

	// (String) The fabric for the network interface.
	// The fabric for the network interface.
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) Static IP configured on the new network interface.
	// Static IP configured on the new network interface.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The network interface name.
	// The network interface name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The subnet CIDR for the network interface.
	// The subnet CIDR for the network interface.
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// (String) The VLAN for the network interface.
	// The VLAN for the network interface.
	Vlan *string `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type NetworkInterfacesParameters struct {

	// (String) The fabric for the network interface.
	// The fabric for the network interface.
	// +kubebuilder:validation:Optional
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) Static IP configured on the new network interface.
	// Static IP configured on the new network interface.
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The network interface name.
	// The network interface name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The subnet CIDR for the network interface.
	// The subnet CIDR for the network interface.
	// +kubebuilder:validation:Optional
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// (String) The VLAN for the network interface.
	// The VLAN for the network interface.
	// +kubebuilder:validation:Optional
	Vlan *string `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type StorageDisksInitParameters struct {

	// (String) The VM host machine pool. This is computed if it's not set.
	// The VM host storage pool name.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// (Number) The storage disk size, specified in GB.
	// The storage disk size, specified in GB.
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`
}

type StorageDisksObservation struct {

	// (String) The VM host machine pool. This is computed if it's not set.
	// The VM host storage pool name.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// (Number) The storage disk size, specified in GB.
	// The storage disk size, specified in GB.
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`
}

type StorageDisksParameters struct {

	// (String) The VM host machine pool. This is computed if it's not set.
	// The VM host storage pool name.
	// +kubebuilder:validation:Optional
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// (Number) The storage disk size, specified in GB.
	// The storage disk size, specified in GB.
	// +kubebuilder:validation:Optional
	SizeGigabytes *float64 `json:"sizeGigabytes" tf:"size_gigabytes,omitempty"`
}

type VMHostMachineInitParameters struct {

	// (Number) The number of CPU cores (defaults to 1).
	// The number of CPU cores (defaults to 1).
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// (String) The VM host machine domain. This is computed if it's not set.
	// The VM host machine domain. This is computed if it's not set.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The VM host machine hostname. This is computed if it's not set.
	// The VM host machine hostname. This is computed if it's not set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (Number) The VM host machine RAM memory, specified in MB (defaults to 2048).
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces []NetworkInterfacesInitParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (Number) List of host CPU cores to pin the VM host machine to. If this is passed, the cores parameter is ignored.
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores *float64 `json:"pinnedCores,omitempty" tf:"pinned_cores,omitempty"`

	// (String) The VM host machine pool. This is computed if it's not set.
	// The VM host machine pool. This is computed if it's not set.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	StorageDisks []StorageDisksInitParameters `json:"storageDisks,omitempty" tf:"storage_disks,omitempty"`

	// (String) ID or name of the VM host used to compose the new machine.
	// ID or name of the VM host used to compose the new machine.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/machine/v1alpha1.VMHost
	VMHost *string `json:"vmHost,omitempty" tf:"vm_host,omitempty"`

	// Reference to a VMHost in machine to populate vmHost.
	// +kubebuilder:validation:Optional
	VMHostRef *v1.Reference `json:"vmHostRef,omitempty" tf:"-"`

	// Selector for a VMHost in machine to populate vmHost.
	// +kubebuilder:validation:Optional
	VMHostSelector *v1.Selector `json:"vmHostSelector,omitempty" tf:"-"`

	// (String) The VM host machine zone. This is computed if it's not set.
	// The VM host machine zone. This is computed if it's not set.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VMHostMachineObservation struct {

	// (Number) The number of CPU cores (defaults to 1).
	// The number of CPU cores (defaults to 1).
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// (String) The VM host machine domain. This is computed if it's not set.
	// The VM host machine domain. This is computed if it's not set.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The VM host machine hostname. This is computed if it's not set.
	// The VM host machine hostname. This is computed if it's not set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) The VM host machine RAM memory, specified in MB (defaults to 2048).
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces []NetworkInterfacesObservation `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (Number) List of host CPU cores to pin the VM host machine to. If this is passed, the cores parameter is ignored.
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores *float64 `json:"pinnedCores,omitempty" tf:"pinned_cores,omitempty"`

	// (String) The VM host machine pool. This is computed if it's not set.
	// The VM host machine pool. This is computed if it's not set.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	StorageDisks []StorageDisksObservation `json:"storageDisks,omitempty" tf:"storage_disks,omitempty"`

	// (String) ID or name of the VM host used to compose the new machine.
	// ID or name of the VM host used to compose the new machine.
	VMHost *string `json:"vmHost,omitempty" tf:"vm_host,omitempty"`

	// (String) The VM host machine zone. This is computed if it's not set.
	// The VM host machine zone. This is computed if it's not set.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VMHostMachineParameters struct {

	// (Number) The number of CPU cores (defaults to 1).
	// The number of CPU cores (defaults to 1).
	// +kubebuilder:validation:Optional
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// (String) The VM host machine domain. This is computed if it's not set.
	// The VM host machine domain. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The VM host machine hostname. This is computed if it's not set.
	// The VM host machine hostname. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (Number) The VM host machine RAM memory, specified in MB (defaults to 2048).
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	// +kubebuilder:validation:Optional
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	// +kubebuilder:validation:Optional
	NetworkInterfaces []NetworkInterfacesParameters `json:"networkInterfaces,omitempty" tf:"network_interfaces,omitempty"`

	// (Number) List of host CPU cores to pin the VM host machine to. If this is passed, the cores parameter is ignored.
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	// +kubebuilder:validation:Optional
	PinnedCores *float64 `json:"pinnedCores,omitempty" tf:"pinned_cores,omitempty"`

	// (String) The VM host machine pool. This is computed if it's not set.
	// The VM host machine pool. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	// +kubebuilder:validation:Optional
	StorageDisks []StorageDisksParameters `json:"storageDisks,omitempty" tf:"storage_disks,omitempty"`

	// (String) ID or name of the VM host used to compose the new machine.
	// ID or name of the VM host used to compose the new machine.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/machine/v1alpha1.VMHost
	// +kubebuilder:validation:Optional
	VMHost *string `json:"vmHost,omitempty" tf:"vm_host,omitempty"`

	// Reference to a VMHost in machine to populate vmHost.
	// +kubebuilder:validation:Optional
	VMHostRef *v1.Reference `json:"vmHostRef,omitempty" tf:"-"`

	// Selector for a VMHost in machine to populate vmHost.
	// +kubebuilder:validation:Optional
	VMHostSelector *v1.Selector `json:"vmHostSelector,omitempty" tf:"-"`

	// (String) The VM host machine zone. This is computed if it's not set.
	// The VM host machine zone. This is computed if it's not set.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// VMHostMachineSpec defines the desired state of VMHostMachine
type VMHostMachineSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VMHostMachineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VMHostMachineInitParameters `json:"initProvider,omitempty"`
}

// VMHostMachineStatus defines the observed state of VMHostMachine.
type VMHostMachineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VMHostMachineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VMHostMachine is the Schema for the VMHostMachines API. Provides a resource to manage MAAS VM host machines.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,maas}
type VMHostMachine struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VMHostMachineSpec   `json:"spec"`
	Status            VMHostMachineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VMHostMachineList contains a list of VMHostMachines
type VMHostMachineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VMHostMachine `json:"items"`
}

// Repository type metadata.
var (
	VMHostMachine_Kind             = "VMHostMachine"
	VMHostMachine_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VMHostMachine_Kind}.String()
	VMHostMachine_KindAPIVersion   = VMHostMachine_Kind + "." + CRDGroupVersion.String()
	VMHostMachine_GroupVersionKind = CRDGroupVersion.WithKind(VMHostMachine_Kind)
)

func init() {
	SchemeBuilder.Register(&VMHostMachine{}, &VMHostMachineList{})
}
