---
# Secret for power parameters (must be created first)
apiVersion: v1
kind: Secret
metadata:
  name: proxmox-vm-power-params
  namespace: crossplane-system
type: Opaque
stringData:
  # For manual power type, empty JSON is required
  # Power control is done via Proxmox UI
  params: "{}"
---
# Proxmox VM managed by MAAS
#
# SETUP:
# 1. Create a VM in Proxmox with:
#    - No boot media (PXE boot)
#    - Network on vmbr1 (provisioning bridge)
#    - Boot order: Network first, then Disk
# 2. Start the VM - it will PXE boot and appear in MAAS
# 3. Get the MAC address from Proxmox UI: VM -> Hardware -> Network Device
# 4. Update pxeMacAddress below with your VM's MAC
#
apiVersion: machine.maas.crossplane.io/v1alpha1
kind: Machine
metadata:
  name: proxmox-vm
spec:
  forProvider:
    # Proxmox VM's MAC address (on vmbr1)
    pxeMacAddress: "BC:24:11:C8:EE:50"

    # Manual power - you control the VM via Proxmox UI
    powerType: manual

    # Empty params for manual power type
    powerParametersSecretRef:
      name: proxmox-vm-power-params
      namespace: crossplane-system
      key: params

    # VM hostname
    hostname: proxmox-vm

    # x86_64 architecture (Proxmox VM)
    architecture: amd64/generic

    # Optional: assign to a resource pool
    # poolRef:
    #   name: proxmox-pool

  providerConfigRef:
    name: default
