// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this InterfaceBond.
func (mg *InterfaceBond) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MachineRef,
		Selector:     mg.Spec.ForProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Machine")
	}
	mg.Spec.ForProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MachineRef,
		Selector:     mg.Spec.InitProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Machine")
	}
	mg.Spec.InitProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this InterfaceBridge.
func (mg *InterfaceBridge) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MachineRef,
		Selector:     mg.Spec.ForProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Machine")
	}
	mg.Spec.ForProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MachineRef,
		Selector:     mg.Spec.InitProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Machine")
	}
	mg.Spec.InitProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this InterfaceLink.
func (mg *InterfaceLink) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MachineRef,
		Selector:     mg.Spec.ForProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Machine")
	}
	mg.Spec.ForProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Subnet),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubnetRef,
		Selector:     mg.Spec.ForProvider.SubnetSelector,
		To: reference.To{
			List:    &SubnetList{},
			Managed: &Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Subnet")
	}
	mg.Spec.ForProvider.Subnet = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MachineRef,
		Selector:     mg.Spec.InitProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Machine")
	}
	mg.Spec.InitProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Subnet),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubnetRef,
		Selector:     mg.Spec.InitProvider.SubnetSelector,
		To: reference.To{
			List:    &SubnetList{},
			Managed: &Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Subnet")
	}
	mg.Spec.InitProvider.Subnet = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this InterfacePhysical.
func (mg *InterfacePhysical) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MachineRef,
		Selector:     mg.Spec.ForProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Machine")
	}
	mg.Spec.ForProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MachineRef,
		Selector:     mg.Spec.InitProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Machine")
	}
	mg.Spec.InitProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this InterfaceVLAN.
func (mg *InterfaceVLAN) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Fabric),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FabricRef,
		Selector:     mg.Spec.ForProvider.FabricSelector,
		To: reference.To{
			List:    &FabricList{},
			Managed: &Fabric{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Fabric")
	}
	mg.Spec.ForProvider.Fabric = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FabricRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MachineRef,
		Selector:     mg.Spec.ForProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Machine")
	}
	mg.Spec.ForProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Fabric),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FabricRef,
		Selector:     mg.Spec.InitProvider.FabricSelector,
		To: reference.To{
			List:    &FabricList{},
			Managed: &Fabric{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Fabric")
	}
	mg.Spec.InitProvider.Fabric = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FabricRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MachineRef,
		Selector:     mg.Spec.InitProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Machine")
	}
	mg.Spec.InitProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Subnet.
func (mg *Subnet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Vlan),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VlanRef,
		Selector:     mg.Spec.ForProvider.VlanSelector,
		To: reference.To{
			List:    &VLANList{},
			Managed: &VLAN{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Vlan")
	}
	mg.Spec.ForProvider.Vlan = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VlanRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Vlan),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VlanRef,
		Selector:     mg.Spec.InitProvider.VlanSelector,
		To: reference.To{
			List:    &VLANList{},
			Managed: &VLAN{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Vlan")
	}
	mg.Spec.InitProvider.Vlan = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VlanRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SubnetIPRange.
func (mg *SubnetIPRange) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Subnet),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubnetRef,
		Selector:     mg.Spec.ForProvider.SubnetSelector,
		To: reference.To{
			List:    &SubnetList{},
			Managed: &Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Subnet")
	}
	mg.Spec.ForProvider.Subnet = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Subnet),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubnetRef,
		Selector:     mg.Spec.InitProvider.SubnetSelector,
		To: reference.To{
			List:    &SubnetList{},
			Managed: &Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Subnet")
	}
	mg.Spec.InitProvider.Subnet = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this VLAN.
func (mg *VLAN) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Fabric),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FabricRef,
		Selector:     mg.Spec.ForProvider.FabricSelector,
		To: reference.To{
			List:    &FabricList{},
			Managed: &Fabric{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Fabric")
	}
	mg.Spec.ForProvider.Fabric = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FabricRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Fabric),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FabricRef,
		Selector:     mg.Spec.InitProvider.FabricSelector,
		To: reference.To{
			List:    &FabricList{},
			Managed: &Fabric{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Fabric")
	}
	mg.Spec.InitProvider.Fabric = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FabricRef = rsp.ResolvedReference

	return nil
}
