// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InterfaceBondInitParameters struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (Number) Specifies the time, in milliseconds, to wait before disabling a slave after a link failure has been detected.
	// Specifies the time, in milliseconds, to wait before disabling a slave after a link failure has been detected.
	BondDowndelay *float64 `json:"bondDowndelay,omitempty" tf:"bond_downdelay,omitempty"`

	// (String) Option specifying the rate at which to ask the link partner to transmit LACPDU packets in 802.3ad mode. Available options are fast or slow. (Default: slow).
	// Option specifying the rate at which to ask the link partner to transmit LACPDU packets in 802.3ad mode. Available options are “fast“ or “slow“. (Default: “slow“).
	BondLacpRate *string `json:"bondLacpRate,omitempty" tf:"bond_lacp_rate,omitempty"`

	// (Number) The link monitoring frequency in milliseconds. (Default: 100).
	// The link monitoring frequency in milliseconds. (Default: 100).
	BondMiimon *float64 `json:"bondMiimon,omitempty" tf:"bond_miimon,omitempty"`

	// backup). Supported bonding modes: - balance-rr: Transmit packets in sequential order from the first available slave through the last. This mode provides load balancing and fault tolerance. - active-backup: Only one slave in the bond is active. A different slave becomes active if, and only if, the active slave fails. The bond's MAC address is externally visible on only one port (network adapter) to avoid confusing the switch. - balance-xor: Transmit based on the selected transmit hash policy. The default policy is a simple [(source MAC address XOR'd with destination MAC address XOR packet type ID) modulo slave count]. - broadcast: Transmits everything on all slave interfaces. This mode provides fault tolerance. - 802.3ad: IEEE 802.3ad dynamic link aggregation. Creates aggregation groups that share the same speed and duplex settings. Uses all slaves in the active aggregator according to the 802.3ad specification. - balance-tlb: Adaptive transmit load balancing: channel bonding that does not require any special switch support. - balance-alb: Adaptive load balancing: includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. The receive load balancing is achieved by ARP negotiation.
	// The operating mode of the bond. (Default: active-backup). Supported bonding modes: - “balance-rr“: Transmit packets in sequential order from the first available slave through the last. This mode provides load balancing and fault tolerance. - “active-backup“: Only one slave in the bond is active. A different slave becomes active if, and only if, the active slave fails. The bond's MAC address is externally visible on only one port (network adapter) to avoid confusing the switch. - “balance-xor“: Transmit based on the selected transmit hash policy. The default policy is a simple [(source MAC address XOR'd with destination MAC address XOR packet type ID) modulo slave count]. - “broadcast“: Transmits everything on all slave interfaces. This mode provides fault tolerance. - “802.3ad“: IEEE 802.3ad dynamic link aggregation. Creates aggregation groups that share the same speed and duplex settings. Uses all slaves in the active aggregator according to the 802.3ad specification. - “balance-tlb“: Adaptive transmit load balancing: channel bonding that does not require any special switch support. - “balance-alb“: Adaptive load balancing: includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. The receive load balancing is achieved by ARP negotiation.
	BondMode *string `json:"bondMode,omitempty" tf:"bond_mode,omitempty"`

	// (Number) The number of peer notifications (IPv4 ARP or IPv6 Neighbour Advertisements) to be issued after a failover. (Default: 1).
	// The number of peer notifications (IPv4 ARP or IPv6 Neighbour Advertisements) to be issued after a failover. (Default: 1).
	BondNumGratArp *float64 `json:"bondNumGratArp,omitempty" tf:"bond_num_grat_arp,omitempty"`

	// (Number) Specifies the time, in milliseconds, to wait before enabling a slave after a link recovery has been detected.
	// Specifies the time, in milliseconds, to wait before enabling a slave after a link recovery has been detected.
	BondUpdelay *float64 `json:"bondUpdelay,omitempty" tf:"bond_updelay,omitempty"`

	// xor, 802.3ad, and tlb modes. Possible values are: layer2, layer2+3, layer3+4, encap2+3, encap3+4. (Default: layer2).
	// The transmit hash policy to use for slave selection in balance-xor, 802.3ad, and tlb modes. Possible values are: “layer2“, “layer2+3“, “layer3+4“, “encap2+3“, “encap3+4“. (Default: “layer2“).
	BondXmitHashPolicy *string `json:"bondXmitHashPolicy,omitempty" tf:"bond_xmit_hash_policy,omitempty"`

	// (String) The bond interface MAC address.
	// The bond interface MAC address.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the bond interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the bond interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the bond interface.
	// The MTU of the bond interface.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The bond interface name.
	// The bond interface name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Parent interface names for this bond interface.
	// Parent interface names for this bond interface.
	// +listType=set
	Parents []*string `json:"parents,omitempty" tf:"parents,omitempty"`

	// (Set of String) A set of tag names to be assigned to the bond interface.
	// A set of tag names to be assigned to the bond interface.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the bond interface is connected to.
	// Database ID of the VLAN the bond interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfaceBondObservation struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (Number) Specifies the time, in milliseconds, to wait before disabling a slave after a link failure has been detected.
	// Specifies the time, in milliseconds, to wait before disabling a slave after a link failure has been detected.
	BondDowndelay *float64 `json:"bondDowndelay,omitempty" tf:"bond_downdelay,omitempty"`

	// (String) Option specifying the rate at which to ask the link partner to transmit LACPDU packets in 802.3ad mode. Available options are fast or slow. (Default: slow).
	// Option specifying the rate at which to ask the link partner to transmit LACPDU packets in 802.3ad mode. Available options are “fast“ or “slow“. (Default: “slow“).
	BondLacpRate *string `json:"bondLacpRate,omitempty" tf:"bond_lacp_rate,omitempty"`

	// (Number) The link monitoring frequency in milliseconds. (Default: 100).
	// The link monitoring frequency in milliseconds. (Default: 100).
	BondMiimon *float64 `json:"bondMiimon,omitempty" tf:"bond_miimon,omitempty"`

	// backup). Supported bonding modes: - balance-rr: Transmit packets in sequential order from the first available slave through the last. This mode provides load balancing and fault tolerance. - active-backup: Only one slave in the bond is active. A different slave becomes active if, and only if, the active slave fails. The bond's MAC address is externally visible on only one port (network adapter) to avoid confusing the switch. - balance-xor: Transmit based on the selected transmit hash policy. The default policy is a simple [(source MAC address XOR'd with destination MAC address XOR packet type ID) modulo slave count]. - broadcast: Transmits everything on all slave interfaces. This mode provides fault tolerance. - 802.3ad: IEEE 802.3ad dynamic link aggregation. Creates aggregation groups that share the same speed and duplex settings. Uses all slaves in the active aggregator according to the 802.3ad specification. - balance-tlb: Adaptive transmit load balancing: channel bonding that does not require any special switch support. - balance-alb: Adaptive load balancing: includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. The receive load balancing is achieved by ARP negotiation.
	// The operating mode of the bond. (Default: active-backup). Supported bonding modes: - “balance-rr“: Transmit packets in sequential order from the first available slave through the last. This mode provides load balancing and fault tolerance. - “active-backup“: Only one slave in the bond is active. A different slave becomes active if, and only if, the active slave fails. The bond's MAC address is externally visible on only one port (network adapter) to avoid confusing the switch. - “balance-xor“: Transmit based on the selected transmit hash policy. The default policy is a simple [(source MAC address XOR'd with destination MAC address XOR packet type ID) modulo slave count]. - “broadcast“: Transmits everything on all slave interfaces. This mode provides fault tolerance. - “802.3ad“: IEEE 802.3ad dynamic link aggregation. Creates aggregation groups that share the same speed and duplex settings. Uses all slaves in the active aggregator according to the 802.3ad specification. - “balance-tlb“: Adaptive transmit load balancing: channel bonding that does not require any special switch support. - “balance-alb“: Adaptive load balancing: includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. The receive load balancing is achieved by ARP negotiation.
	BondMode *string `json:"bondMode,omitempty" tf:"bond_mode,omitempty"`

	// (Number) The number of peer notifications (IPv4 ARP or IPv6 Neighbour Advertisements) to be issued after a failover. (Default: 1).
	// The number of peer notifications (IPv4 ARP or IPv6 Neighbour Advertisements) to be issued after a failover. (Default: 1).
	BondNumGratArp *float64 `json:"bondNumGratArp,omitempty" tf:"bond_num_grat_arp,omitempty"`

	// (Number) Specifies the time, in milliseconds, to wait before enabling a slave after a link recovery has been detected.
	// Specifies the time, in milliseconds, to wait before enabling a slave after a link recovery has been detected.
	BondUpdelay *float64 `json:"bondUpdelay,omitempty" tf:"bond_updelay,omitempty"`

	// xor, 802.3ad, and tlb modes. Possible values are: layer2, layer2+3, layer3+4, encap2+3, encap3+4. (Default: layer2).
	// The transmit hash policy to use for slave selection in balance-xor, 802.3ad, and tlb modes. Possible values are: “layer2“, “layer2+3“, “layer3+4“, “encap2+3“, “encap3+4“. (Default: “layer2“).
	BondXmitHashPolicy *string `json:"bondXmitHashPolicy,omitempty" tf:"bond_xmit_hash_policy,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The bond interface MAC address.
	// The bond interface MAC address.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the bond interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the bond interface.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The MTU of the bond interface.
	// The MTU of the bond interface.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The bond interface name.
	// The bond interface name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Parent interface names for this bond interface.
	// Parent interface names for this bond interface.
	// +listType=set
	Parents []*string `json:"parents,omitempty" tf:"parents,omitempty"`

	// (Set of String) A set of tag names to be assigned to the bond interface.
	// A set of tag names to be assigned to the bond interface.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the bond interface is connected to.
	// Database ID of the VLAN the bond interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfaceBondParameters struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	// +kubebuilder:validation:Optional
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (Number) Specifies the time, in milliseconds, to wait before disabling a slave after a link failure has been detected.
	// Specifies the time, in milliseconds, to wait before disabling a slave after a link failure has been detected.
	// +kubebuilder:validation:Optional
	BondDowndelay *float64 `json:"bondDowndelay,omitempty" tf:"bond_downdelay,omitempty"`

	// (String) Option specifying the rate at which to ask the link partner to transmit LACPDU packets in 802.3ad mode. Available options are fast or slow. (Default: slow).
	// Option specifying the rate at which to ask the link partner to transmit LACPDU packets in 802.3ad mode. Available options are “fast“ or “slow“. (Default: “slow“).
	// +kubebuilder:validation:Optional
	BondLacpRate *string `json:"bondLacpRate,omitempty" tf:"bond_lacp_rate,omitempty"`

	// (Number) The link monitoring frequency in milliseconds. (Default: 100).
	// The link monitoring frequency in milliseconds. (Default: 100).
	// +kubebuilder:validation:Optional
	BondMiimon *float64 `json:"bondMiimon,omitempty" tf:"bond_miimon,omitempty"`

	// backup). Supported bonding modes: - balance-rr: Transmit packets in sequential order from the first available slave through the last. This mode provides load balancing and fault tolerance. - active-backup: Only one slave in the bond is active. A different slave becomes active if, and only if, the active slave fails. The bond's MAC address is externally visible on only one port (network adapter) to avoid confusing the switch. - balance-xor: Transmit based on the selected transmit hash policy. The default policy is a simple [(source MAC address XOR'd with destination MAC address XOR packet type ID) modulo slave count]. - broadcast: Transmits everything on all slave interfaces. This mode provides fault tolerance. - 802.3ad: IEEE 802.3ad dynamic link aggregation. Creates aggregation groups that share the same speed and duplex settings. Uses all slaves in the active aggregator according to the 802.3ad specification. - balance-tlb: Adaptive transmit load balancing: channel bonding that does not require any special switch support. - balance-alb: Adaptive load balancing: includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. The receive load balancing is achieved by ARP negotiation.
	// The operating mode of the bond. (Default: active-backup). Supported bonding modes: - “balance-rr“: Transmit packets in sequential order from the first available slave through the last. This mode provides load balancing and fault tolerance. - “active-backup“: Only one slave in the bond is active. A different slave becomes active if, and only if, the active slave fails. The bond's MAC address is externally visible on only one port (network adapter) to avoid confusing the switch. - “balance-xor“: Transmit based on the selected transmit hash policy. The default policy is a simple [(source MAC address XOR'd with destination MAC address XOR packet type ID) modulo slave count]. - “broadcast“: Transmits everything on all slave interfaces. This mode provides fault tolerance. - “802.3ad“: IEEE 802.3ad dynamic link aggregation. Creates aggregation groups that share the same speed and duplex settings. Uses all slaves in the active aggregator according to the 802.3ad specification. - “balance-tlb“: Adaptive transmit load balancing: channel bonding that does not require any special switch support. - “balance-alb“: Adaptive load balancing: includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. The receive load balancing is achieved by ARP negotiation.
	// +kubebuilder:validation:Optional
	BondMode *string `json:"bondMode,omitempty" tf:"bond_mode,omitempty"`

	// (Number) The number of peer notifications (IPv4 ARP or IPv6 Neighbour Advertisements) to be issued after a failover. (Default: 1).
	// The number of peer notifications (IPv4 ARP or IPv6 Neighbour Advertisements) to be issued after a failover. (Default: 1).
	// +kubebuilder:validation:Optional
	BondNumGratArp *float64 `json:"bondNumGratArp,omitempty" tf:"bond_num_grat_arp,omitempty"`

	// (Number) Specifies the time, in milliseconds, to wait before enabling a slave after a link recovery has been detected.
	// Specifies the time, in milliseconds, to wait before enabling a slave after a link recovery has been detected.
	// +kubebuilder:validation:Optional
	BondUpdelay *float64 `json:"bondUpdelay,omitempty" tf:"bond_updelay,omitempty"`

	// xor, 802.3ad, and tlb modes. Possible values are: layer2, layer2+3, layer3+4, encap2+3, encap3+4. (Default: layer2).
	// The transmit hash policy to use for slave selection in balance-xor, 802.3ad, and tlb modes. Possible values are: “layer2“, “layer2+3“, “layer3+4“, “encap2+3“, “encap3+4“. (Default: “layer2“).
	// +kubebuilder:validation:Optional
	BondXmitHashPolicy *string `json:"bondXmitHashPolicy,omitempty" tf:"bond_xmit_hash_policy,omitempty"`

	// (String) The bond interface MAC address.
	// The bond interface MAC address.
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the bond interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the bond interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the bond interface.
	// The MTU of the bond interface.
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The bond interface name.
	// The bond interface name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Parent interface names for this bond interface.
	// Parent interface names for this bond interface.
	// +kubebuilder:validation:Optional
	// +listType=set
	Parents []*string `json:"parents,omitempty" tf:"parents,omitempty"`

	// (Set of String) A set of tag names to be assigned to the bond interface.
	// A set of tag names to be assigned to the bond interface.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the bond interface is connected to.
	// Database ID of the VLAN the bond interface is connected to.
	// +kubebuilder:validation:Optional
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

// InterfaceBondSpec defines the desired state of InterfaceBond
type InterfaceBondSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InterfaceBondParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InterfaceBondInitParameters `json:"initProvider,omitempty"`
}

// InterfaceBondStatus defines the observed state of InterfaceBond.
type InterfaceBondStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InterfaceBondObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InterfaceBond is the Schema for the InterfaceBonds API. Provides a resource to manage MAAS network Bonds.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type InterfaceBond struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parents) || (has(self.initProvider) && has(self.initProvider.parents))",message="spec.forProvider.parents is a required parameter"
	Spec   InterfaceBondSpec   `json:"spec"`
	Status InterfaceBondStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceBondList contains a list of InterfaceBonds
type InterfaceBondList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfaceBond `json:"items"`
}

// Repository type metadata.
var (
	InterfaceBond_Kind             = "InterfaceBond"
	InterfaceBond_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfaceBond_Kind}.String()
	InterfaceBond_KindAPIVersion   = InterfaceBond_Kind + "." + CRDGroupVersion.String()
	InterfaceBond_GroupVersionKind = CRDGroupVersion.WithKind(InterfaceBond_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfaceBond{}, &InterfaceBondList{})
}
