// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InterfaceLinkInitParameters struct {

	// (Boolean) Boolean value. When enabled, it sets the subnet gateway IP address as the default gateway for the machine the interface belongs to. This option can only be used with the AUTO and STATIC modes. Defaults to false.
	// Boolean value. When enabled, it sets the subnet gateway IP address as the default gateway for the machine the interface belongs to. This option can only be used with the `AUTO` and `STATIC` modes. Defaults to `false`.
	DefaultGateway *bool `json:"defaultGateway,omitempty" tf:"default_gateway,omitempty"`

	// The identifier (system ID, hostname, or FQDN) of the device with the network interface. Either `machine` or `device` must be provided.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Valid IP address (from the given subnet) to be configured on the network interface. Only used when mode is set to STATIC.
	// Valid IP address (from the given subnet) to be configured on the network interface. Only used when `mode` is set to `STATIC`.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the network interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the network interface. Either `machine` or `device` must be provided.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (String) Connection mode to subnet. It defaults to AUTO. Valid options are:
	// Connection mode to subnet. It defaults to `AUTO`. Valid options are:
	// * `AUTO` - Random static IP address from the subnet.
	// * `DHCP` - IP address from the DHCP on the given subnet.
	// * `STATIC` - Use `ip_address` as static IP address.
	// * `LINK_UP` - Bring the interface up only on the given subnet. No IP address will be assigned.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The identifier (MAC address, name, or ID) of the network interface.
	// The identifier (MAC address, name, or ID) of the network interface.
	NetworkInterface *string `json:"networkInterface,omitempty" tf:"network_interface,omitempty"`

	// (String) The identifier (CIDR or ID) of the subnet to be connected.
	// The identifier (CIDR or ID) of the subnet to be connected.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/network/v1alpha1.Subnet
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// Reference to a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetRef *v1.NamespacedReference `json:"subnetRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetSelector *v1.NamespacedSelector `json:"subnetSelector,omitempty" tf:"-"`
}

type InterfaceLinkObservation struct {

	// (Boolean) Boolean value. When enabled, it sets the subnet gateway IP address as the default gateway for the machine the interface belongs to. This option can only be used with the AUTO and STATIC modes. Defaults to false.
	// Boolean value. When enabled, it sets the subnet gateway IP address as the default gateway for the machine the interface belongs to. This option can only be used with the `AUTO` and `STATIC` modes. Defaults to `false`.
	DefaultGateway *bool `json:"defaultGateway,omitempty" tf:"default_gateway,omitempty"`

	// The identifier (system ID, hostname, or FQDN) of the device with the network interface. Either `machine` or `device` must be provided.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Valid IP address (from the given subnet) to be configured on the network interface. Only used when mode is set to STATIC.
	// Valid IP address (from the given subnet) to be configured on the network interface. Only used when `mode` is set to `STATIC`.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the network interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the network interface. Either `machine` or `device` must be provided.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (String) Connection mode to subnet. It defaults to AUTO. Valid options are:
	// Connection mode to subnet. It defaults to `AUTO`. Valid options are:
	// * `AUTO` - Random static IP address from the subnet.
	// * `DHCP` - IP address from the DHCP on the given subnet.
	// * `STATIC` - Use `ip_address` as static IP address.
	// * `LINK_UP` - Bring the interface up only on the given subnet. No IP address will be assigned.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The identifier (MAC address, name, or ID) of the network interface.
	// The identifier (MAC address, name, or ID) of the network interface.
	NetworkInterface *string `json:"networkInterface,omitempty" tf:"network_interface,omitempty"`

	// (String) The identifier (CIDR or ID) of the subnet to be connected.
	// The identifier (CIDR or ID) of the subnet to be connected.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type InterfaceLinkParameters struct {

	// (Boolean) Boolean value. When enabled, it sets the subnet gateway IP address as the default gateway for the machine the interface belongs to. This option can only be used with the AUTO and STATIC modes. Defaults to false.
	// Boolean value. When enabled, it sets the subnet gateway IP address as the default gateway for the machine the interface belongs to. This option can only be used with the `AUTO` and `STATIC` modes. Defaults to `false`.
	// +kubebuilder:validation:Optional
	DefaultGateway *bool `json:"defaultGateway,omitempty" tf:"default_gateway,omitempty"`

	// The identifier (system ID, hostname, or FQDN) of the device with the network interface. Either `machine` or `device` must be provided.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Valid IP address (from the given subnet) to be configured on the network interface. Only used when mode is set to STATIC.
	// Valid IP address (from the given subnet) to be configured on the network interface. Only used when `mode` is set to `STATIC`.
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the network interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the network interface. Either `machine` or `device` must be provided.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (String) Connection mode to subnet. It defaults to AUTO. Valid options are:
	// Connection mode to subnet. It defaults to `AUTO`. Valid options are:
	// * `AUTO` - Random static IP address from the subnet.
	// * `DHCP` - IP address from the DHCP on the given subnet.
	// * `STATIC` - Use `ip_address` as static IP address.
	// * `LINK_UP` - Bring the interface up only on the given subnet. No IP address will be assigned.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The identifier (MAC address, name, or ID) of the network interface.
	// The identifier (MAC address, name, or ID) of the network interface.
	// +kubebuilder:validation:Optional
	NetworkInterface *string `json:"networkInterface,omitempty" tf:"network_interface,omitempty"`

	// (String) The identifier (CIDR or ID) of the subnet to be connected.
	// The identifier (CIDR or ID) of the subnet to be connected.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// Reference to a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetRef *v1.NamespacedReference `json:"subnetRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetSelector *v1.NamespacedSelector `json:"subnetSelector,omitempty" tf:"-"`
}

// InterfaceLinkSpec defines the desired state of InterfaceLink
type InterfaceLinkSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InterfaceLinkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InterfaceLinkInitParameters `json:"initProvider,omitempty"`
}

// InterfaceLinkStatus defines the observed state of InterfaceLink.
type InterfaceLinkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InterfaceLinkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InterfaceLink is the Schema for the InterfaceLinks API. Provides a resource to manage network configuration on a network interface.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type InterfaceLink struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkInterface) || (has(self.initProvider) && has(self.initProvider.networkInterface))",message="spec.forProvider.networkInterface is a required parameter"
	Spec   InterfaceLinkSpec   `json:"spec"`
	Status InterfaceLinkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceLinkList contains a list of InterfaceLinks
type InterfaceLinkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfaceLink `json:"items"`
}

// Repository type metadata.
var (
	InterfaceLink_Kind             = "InterfaceLink"
	InterfaceLink_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfaceLink_Kind}.String()
	InterfaceLink_KindAPIVersion   = InterfaceLink_Kind + "." + CRDGroupVersion.String()
	InterfaceLink_GroupVersionKind = CRDGroupVersion.WithKind(InterfaceLink_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfaceLink{}, &InterfaceLinkList{})
}
