// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InterfacePhysicalInitParameters struct {

	// (String) The physical network interface MAC address.
	// The physical network interface MAC address.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the physical network interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the physical network interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the physical network interface. This argument is computed if it's not set.
	// The MTU of the physical network interface. This argument is computed if it's not set.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The physical network interface name. This argument is computed if it's not set.
	// The physical network interface name. This argument is computed if it's not set.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A set of tag names to be assigned to the physical network interface. This argument is computed if it's not set.
	// A set of tag names to be assigned to the physical network interface. This argument is computed if it's not set.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the physical network interface is connected to.
	// Database ID of the VLAN the physical network interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfacePhysicalObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The physical network interface MAC address.
	// The physical network interface MAC address.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the physical network interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the physical network interface.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The MTU of the physical network interface. This argument is computed if it's not set.
	// The MTU of the physical network interface. This argument is computed if it's not set.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The physical network interface name. This argument is computed if it's not set.
	// The physical network interface name. This argument is computed if it's not set.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A set of tag names to be assigned to the physical network interface. This argument is computed if it's not set.
	// A set of tag names to be assigned to the physical network interface. This argument is computed if it's not set.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the physical network interface is connected to.
	// Database ID of the VLAN the physical network interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfacePhysicalParameters struct {

	// (String) The physical network interface MAC address.
	// The physical network interface MAC address.
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the physical network interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the physical network interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the physical network interface. This argument is computed if it's not set.
	// The MTU of the physical network interface. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The physical network interface name. This argument is computed if it's not set.
	// The physical network interface name. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A set of tag names to be assigned to the physical network interface. This argument is computed if it's not set.
	// A set of tag names to be assigned to the physical network interface. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the physical network interface is connected to.
	// Database ID of the VLAN the physical network interface is connected to.
	// +kubebuilder:validation:Optional
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

// InterfacePhysicalSpec defines the desired state of InterfacePhysical
type InterfacePhysicalSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InterfacePhysicalParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InterfacePhysicalInitParameters `json:"initProvider,omitempty"`
}

// InterfacePhysicalStatus defines the observed state of InterfacePhysical.
type InterfacePhysicalStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InterfacePhysicalObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InterfacePhysical is the Schema for the InterfacePhysicals API. Provides a resource to manage a physical network interface from an existing MAAS machine.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type InterfacePhysical struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.macAddress) || (has(self.initProvider) && has(self.initProvider.macAddress))",message="spec.forProvider.macAddress is a required parameter"
	Spec   InterfacePhysicalSpec   `json:"spec"`
	Status InterfacePhysicalStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfacePhysicalList contains a list of InterfacePhysicals
type InterfacePhysicalList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfacePhysical `json:"items"`
}

// Repository type metadata.
var (
	InterfacePhysical_Kind             = "InterfacePhysical"
	InterfacePhysical_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfacePhysical_Kind}.String()
	InterfacePhysical_KindAPIVersion   = InterfacePhysical_Kind + "." + CRDGroupVersion.String()
	InterfacePhysical_GroupVersionKind = CRDGroupVersion.WithKind(InterfacePhysical_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfacePhysical{}, &InterfacePhysicalList{})
}
