// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IPRangesInitParameters struct {

	// (String) A description of this range.
	// A description of this range.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The end IP for the new IP range (inclusive).
	// The end IP for the new IP range (inclusive).
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (String) The start IP for the new IP range (inclusive).
	// The start IP for the new IP range (inclusive).
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) The IP range type. Valid options are: dynamic, reserved.
	// The IP range type. Valid options are: `dynamic`, `reserved`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IPRangesObservation struct {

	// (String) A description of this range.
	// A description of this range.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The end IP for the new IP range (inclusive).
	// The end IP for the new IP range (inclusive).
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (String) The start IP for the new IP range (inclusive).
	// The start IP for the new IP range (inclusive).
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) The IP range type. Valid options are: dynamic, reserved.
	// The IP range type. Valid options are: `dynamic`, `reserved`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IPRangesParameters struct {

	// (String) A description of this range.
	// A description of this range.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The end IP for the new IP range (inclusive).
	// The end IP for the new IP range (inclusive).
	// +kubebuilder:validation:Optional
	EndIP *string `json:"endIp" tf:"end_ip,omitempty"`

	// (String) The start IP for the new IP range (inclusive).
	// The start IP for the new IP range (inclusive).
	// +kubebuilder:validation:Optional
	StartIP *string `json:"startIp" tf:"start_ip,omitempty"`

	// (String) The IP range type. Valid options are: dynamic, reserved.
	// The IP range type. Valid options are: `dynamic`, `reserved`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type SubnetInitParameters struct {

	// (Boolean) Boolean value that indicates if the MAAS DNS resolution is enabled for this subnet. Defaults to true.
	// Boolean value that indicates if the MAAS DNS resolution is enabled for this subnet. Defaults to `true`.
	AllowDNS *bool `json:"allowDns,omitempty" tf:"allow_dns,omitempty"`

	// proxy allows requests from this subnet. Defaults to true.
	// Boolean value that indicates if `maas-proxy` allows requests from this subnet. Defaults to `true`.
	AllowProxy *bool `json:"allowProxy,omitempty" tf:"allow_proxy,omitempty"`

	// (String) The subnet CIDR.
	// The subnet CIDR.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (List of String) List of IP addresses set as DNS servers for the new subnet. This argument is computed if it's not set.
	// List of IP addresses set as DNS servers for the new subnet. This argument is computed if it's not set.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// (String) The fabric identifier (ID or name) for the new subnet.
	// The fabric identifier (ID or name) for the new subnet.
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) Gateway IP address for the new subnet. This argument is computed if it's not set.
	// Gateway IP address for the new subnet. This argument is computed if it's not set.
	GatewayIP *string `json:"gatewayIp,omitempty" tf:"gateway_ip,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A set of IP ranges configured on the new subnet. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	IPRanges []IPRangesInitParameters `json:"ipRanges,omitempty" tf:"ip_ranges,omitempty"`

	// (String) The subnet name.
	// The subnet name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) How reverse DNS is handled for this subnet. Defaults to 2. Valid options are:
	// How reverse DNS is handled for this subnet. Defaults to `2`. Valid options are:
	// * `0` - Disabled, no reverse zone is created.
	// * `1` - Enabled, generate reverse zone.
	// * `2` - RFC2317, extends `1` to create the necessary parent zone with the appropriate CNAME resource records for the network, if the network is small enough to require the support described in RFC2317.
	RdnsMode *float64 `json:"rdnsMode,omitempty" tf:"rdns_mode,omitempty"`

	// (String) The VLAN identifier (ID or traffic segregation ID) for the new subnet. If this is set, the fabric argument is required.
	// The VLAN identifier (ID or traffic segregation ID) for the new subnet. If this is set, the `fabric` argument is required.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/network/v1alpha1.VLAN
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	Vlan *string `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// Reference to a VLAN in network to populate vlan.
	// +kubebuilder:validation:Optional
	VlanRef *v1.NamespacedReference `json:"vlanRef,omitempty" tf:"-"`

	// Selector for a VLAN in network to populate vlan.
	// +kubebuilder:validation:Optional
	VlanSelector *v1.NamespacedSelector `json:"vlanSelector,omitempty" tf:"-"`
}

type SubnetObservation struct {

	// (Boolean) Boolean value that indicates if the MAAS DNS resolution is enabled for this subnet. Defaults to true.
	// Boolean value that indicates if the MAAS DNS resolution is enabled for this subnet. Defaults to `true`.
	AllowDNS *bool `json:"allowDns,omitempty" tf:"allow_dns,omitempty"`

	// proxy allows requests from this subnet. Defaults to true.
	// Boolean value that indicates if `maas-proxy` allows requests from this subnet. Defaults to `true`.
	AllowProxy *bool `json:"allowProxy,omitempty" tf:"allow_proxy,omitempty"`

	// (String) The subnet CIDR.
	// The subnet CIDR.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (List of String) List of IP addresses set as DNS servers for the new subnet. This argument is computed if it's not set.
	// List of IP addresses set as DNS servers for the new subnet. This argument is computed if it's not set.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// (String) The fabric identifier (ID or name) for the new subnet.
	// The fabric identifier (ID or name) for the new subnet.
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) Gateway IP address for the new subnet. This argument is computed if it's not set.
	// Gateway IP address for the new subnet. This argument is computed if it's not set.
	GatewayIP *string `json:"gatewayIp,omitempty" tf:"gateway_ip,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A set of IP ranges configured on the new subnet. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	IPRanges []IPRangesObservation `json:"ipRanges,omitempty" tf:"ip_ranges,omitempty"`

	// (String) The subnet name.
	// The subnet name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) How reverse DNS is handled for this subnet. Defaults to 2. Valid options are:
	// How reverse DNS is handled for this subnet. Defaults to `2`. Valid options are:
	// * `0` - Disabled, no reverse zone is created.
	// * `1` - Enabled, generate reverse zone.
	// * `2` - RFC2317, extends `1` to create the necessary parent zone with the appropriate CNAME resource records for the network, if the network is small enough to require the support described in RFC2317.
	RdnsMode *float64 `json:"rdnsMode,omitempty" tf:"rdns_mode,omitempty"`

	// (String) The VLAN identifier (ID or traffic segregation ID) for the new subnet. If this is set, the fabric argument is required.
	// The VLAN identifier (ID or traffic segregation ID) for the new subnet. If this is set, the `fabric` argument is required.
	Vlan *string `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type SubnetParameters struct {

	// (Boolean) Boolean value that indicates if the MAAS DNS resolution is enabled for this subnet. Defaults to true.
	// Boolean value that indicates if the MAAS DNS resolution is enabled for this subnet. Defaults to `true`.
	// +kubebuilder:validation:Optional
	AllowDNS *bool `json:"allowDns,omitempty" tf:"allow_dns,omitempty"`

	// proxy allows requests from this subnet. Defaults to true.
	// Boolean value that indicates if `maas-proxy` allows requests from this subnet. Defaults to `true`.
	// +kubebuilder:validation:Optional
	AllowProxy *bool `json:"allowProxy,omitempty" tf:"allow_proxy,omitempty"`

	// (String) The subnet CIDR.
	// The subnet CIDR.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (List of String) List of IP addresses set as DNS servers for the new subnet. This argument is computed if it's not set.
	// List of IP addresses set as DNS servers for the new subnet. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// (String) The fabric identifier (ID or name) for the new subnet.
	// The fabric identifier (ID or name) for the new subnet.
	// +kubebuilder:validation:Optional
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) Gateway IP address for the new subnet. This argument is computed if it's not set.
	// Gateway IP address for the new subnet. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	GatewayIP *string `json:"gatewayIp,omitempty" tf:"gateway_ip,omitempty"`

	// as-blocks mode. (see below for nested schema)
	// A set of IP ranges configured on the new subnet. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html).
	// +kubebuilder:validation:Optional
	IPRanges []IPRangesParameters `json:"ipRanges,omitempty" tf:"ip_ranges,omitempty"`

	// (String) The subnet name.
	// The subnet name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) How reverse DNS is handled for this subnet. Defaults to 2. Valid options are:
	// How reverse DNS is handled for this subnet. Defaults to `2`. Valid options are:
	// * `0` - Disabled, no reverse zone is created.
	// * `1` - Enabled, generate reverse zone.
	// * `2` - RFC2317, extends `1` to create the necessary parent zone with the appropriate CNAME resource records for the network, if the network is small enough to require the support described in RFC2317.
	// +kubebuilder:validation:Optional
	RdnsMode *float64 `json:"rdnsMode,omitempty" tf:"rdns_mode,omitempty"`

	// (String) The VLAN identifier (ID or traffic segregation ID) for the new subnet. If this is set, the fabric argument is required.
	// The VLAN identifier (ID or traffic segregation ID) for the new subnet. If this is set, the `fabric` argument is required.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/network/v1alpha1.VLAN
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	Vlan *string `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// Reference to a VLAN in network to populate vlan.
	// +kubebuilder:validation:Optional
	VlanRef *v1.NamespacedReference `json:"vlanRef,omitempty" tf:"-"`

	// Selector for a VLAN in network to populate vlan.
	// +kubebuilder:validation:Optional
	VlanSelector *v1.NamespacedSelector `json:"vlanSelector,omitempty" tf:"-"`
}

// SubnetSpec defines the desired state of Subnet
type SubnetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SubnetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetInitParameters `json:"initProvider,omitempty"`
}

// SubnetStatus defines the observed state of Subnet.
type SubnetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Subnet is the Schema for the Subnets API. Provides a resource to manage MAAS network subnets. NOTE: The MAAS provider currently supports both standalone resources and in-line resources for subnet IP ranges. You cannot use in-line ip_ranges in conjunction with standalone maas_subnet_ip_range resources. Doing so will cause conflicts and will overwrite subnet IP ranges.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type Subnet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cidr) || (has(self.initProvider) && has(self.initProvider.cidr))",message="spec.forProvider.cidr is a required parameter"
	Spec   SubnetSpec   `json:"spec"`
	Status SubnetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetList contains a list of Subnets
type SubnetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subnet `json:"items"`
}

// Repository type metadata.
var (
	Subnet_Kind             = "Subnet"
	Subnet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subnet_Kind}.String()
	Subnet_KindAPIVersion   = Subnet_Kind + "." + CRDGroupVersion.String()
	Subnet_GroupVersionKind = CRDGroupVersion.WithKind(Subnet_Kind)
)

func init() {
	SchemeBuilder.Register(&Subnet{}, &SubnetList{})
}
