// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type VLANInitParameters struct {

	// (Boolean) Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
	// Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
	DHCPOn *bool `json:"dhcpOn,omitempty" tf:"dhcp_on,omitempty"`

	// (String) The identifier (name or ID) of the fabric for the new VLAN.
	// The identifier (name or ID) of the fabric for the new VLAN.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/network/v1alpha1.Fabric
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name", true)
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// Reference to a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricRef *v1.NamespacedReference `json:"fabricRef,omitempty" tf:"-"`

	// Selector for a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricSelector *v1.NamespacedSelector `json:"fabricSelector,omitempty" tf:"-"`

	// (Number) The MTU to use on the new VLAN. This argument is computed if it's not set.
	// The MTU to use on the new VLAN. This argument is computed if it's not set.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The name of the new VLAN. This argument is computed if it's not set.
	// The name of the new VLAN. This argument is computed if it's not set.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The space of the new VLAN. Passing in an empty string (or the string undefined) will cause the VLAN to be placed in the undefined space. This argument is computed if it's not set.
	// The space of the new VLAN. Passing in an empty string (or the string `undefined`) will cause the VLAN to be placed in the `undefined` space. This argument is computed if it's not set.
	Space *string `json:"space,omitempty" tf:"space,omitempty"`

	// (Number) The traffic segregation ID for the new VLAN.
	// The traffic segregation ID for the new VLAN.
	Vid *float64 `json:"vid,omitempty" tf:"vid,omitempty"`
}

type VLANObservation struct {

	// (Boolean) Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
	// Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
	DHCPOn *bool `json:"dhcpOn,omitempty" tf:"dhcp_on,omitempty"`

	// (String) The identifier (name or ID) of the fabric for the new VLAN.
	// The identifier (name or ID) of the fabric for the new VLAN.
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) The MTU to use on the new VLAN. This argument is computed if it's not set.
	// The MTU to use on the new VLAN. This argument is computed if it's not set.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The name of the new VLAN. This argument is computed if it's not set.
	// The name of the new VLAN. This argument is computed if it's not set.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The space of the new VLAN. Passing in an empty string (or the string undefined) will cause the VLAN to be placed in the undefined space. This argument is computed if it's not set.
	// The space of the new VLAN. Passing in an empty string (or the string `undefined`) will cause the VLAN to be placed in the `undefined` space. This argument is computed if it's not set.
	Space *string `json:"space,omitempty" tf:"space,omitempty"`

	// (Number) The traffic segregation ID for the new VLAN.
	// The traffic segregation ID for the new VLAN.
	Vid *float64 `json:"vid,omitempty" tf:"vid,omitempty"`
}

type VLANParameters struct {

	// (Boolean) Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
	// Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	DHCPOn *bool `json:"dhcpOn,omitempty" tf:"dhcp_on,omitempty"`

	// (String) The identifier (name or ID) of the fabric for the new VLAN.
	// The identifier (name or ID) of the fabric for the new VLAN.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/network/v1alpha1.Fabric
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name", true)
	// +kubebuilder:validation:Optional
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// Reference to a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricRef *v1.NamespacedReference `json:"fabricRef,omitempty" tf:"-"`

	// Selector for a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricSelector *v1.NamespacedSelector `json:"fabricSelector,omitempty" tf:"-"`

	// (Number) The MTU to use on the new VLAN. This argument is computed if it's not set.
	// The MTU to use on the new VLAN. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The name of the new VLAN. This argument is computed if it's not set.
	// The name of the new VLAN. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The space of the new VLAN. Passing in an empty string (or the string undefined) will cause the VLAN to be placed in the undefined space. This argument is computed if it's not set.
	// The space of the new VLAN. Passing in an empty string (or the string `undefined`) will cause the VLAN to be placed in the `undefined` space. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	Space *string `json:"space,omitempty" tf:"space,omitempty"`

	// (Number) The traffic segregation ID for the new VLAN.
	// The traffic segregation ID for the new VLAN.
	// +kubebuilder:validation:Optional
	Vid *float64 `json:"vid,omitempty" tf:"vid,omitempty"`
}

// VLANSpec defines the desired state of VLAN
type VLANSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VLANParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VLANInitParameters `json:"initProvider,omitempty"`
}

// VLANStatus defines the observed state of VLAN.
type VLANStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VLANObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VLAN is the Schema for the VLANs API. Provides a resource to manage MAAS network VLANs.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type VLAN struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vid) || (has(self.initProvider) && has(self.initProvider.vid))",message="spec.forProvider.vid is a required parameter"
	Spec   VLANSpec   `json:"spec"`
	Status VLANStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VLANList contains a list of VLANs
type VLANList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VLAN `json:"items"`
}

// Repository type metadata.
var (
	VLAN_Kind             = "VLAN"
	VLAN_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VLAN_Kind}.String()
	VLAN_KindAPIVersion   = VLAN_Kind + "." + CRDGroupVersion.String()
	VLAN_GroupVersionKind = CRDGroupVersion.WithKind(VLAN_Kind)
)

func init() {
	SchemeBuilder.Register(&VLAN{}, &VLANList{})
}
