// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Fabric) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InterfaceBond) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InterfaceBridge) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InterfaceLink) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InterfacePhysical) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InterfaceVLAN) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Space) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subnet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SubnetIPRange) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VLAN) Hub() {}
