// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type InterfaceBridgeInitParameters struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (Number) Set bridge forward delay to time seconds. (Default: 15).
	// Set bridge forward delay to time seconds. (Default: 15).
	BridgeFd *float64 `json:"bridgeFd,omitempty" tf:"bridge_fd,omitempty"`

	// (Boolean) Turn spanning tree protocol on or off. (Default: False).
	// Turn spanning tree protocol on or off. (Default: False).
	BridgeStp *bool `json:"bridgeStp,omitempty" tf:"bridge_stp,omitempty"`

	// (String) The type of bridge to create. Possible values are: standard, ovs.
	// The type of bridge to create. Possible values are: “standard“, “ovs“.
	BridgeType *string `json:"bridgeType,omitempty" tf:"bridge_type,omitempty"`

	// (String) The bridge interface MAC address.
	// The bridge interface MAC address.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the bridge interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the bridge interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/machine/v1alpha1.Machine
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.Reference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.Selector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the bridge interface.
	// The MTU of the bridge interface.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The bridge interface name.
	// The bridge interface name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent interface name for this bridge interface.
	// Parent interface name for this bridge interface.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (Set of String) A set of tag names to be assigned to the bridge interface.
	// A set of tag names to be assigned to the bridge interface.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the bridge interface is connected to.
	// Database ID of the VLAN the bridge interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfaceBridgeObservation struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (Number) Set bridge forward delay to time seconds. (Default: 15).
	// Set bridge forward delay to time seconds. (Default: 15).
	BridgeFd *float64 `json:"bridgeFd,omitempty" tf:"bridge_fd,omitempty"`

	// (Boolean) Turn spanning tree protocol on or off. (Default: False).
	// Turn spanning tree protocol on or off. (Default: False).
	BridgeStp *bool `json:"bridgeStp,omitempty" tf:"bridge_stp,omitempty"`

	// (String) The type of bridge to create. Possible values are: standard, ovs.
	// The type of bridge to create. Possible values are: “standard“, “ovs“.
	BridgeType *string `json:"bridgeType,omitempty" tf:"bridge_type,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The bridge interface MAC address.
	// The bridge interface MAC address.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the bridge interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the bridge interface.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The MTU of the bridge interface.
	// The MTU of the bridge interface.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The bridge interface name.
	// The bridge interface name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent interface name for this bridge interface.
	// Parent interface name for this bridge interface.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (Set of String) A set of tag names to be assigned to the bridge interface.
	// A set of tag names to be assigned to the bridge interface.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the bridge interface is connected to.
	// Database ID of the VLAN the bridge interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfaceBridgeParameters struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	// +kubebuilder:validation:Optional
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (Number) Set bridge forward delay to time seconds. (Default: 15).
	// Set bridge forward delay to time seconds. (Default: 15).
	// +kubebuilder:validation:Optional
	BridgeFd *float64 `json:"bridgeFd,omitempty" tf:"bridge_fd,omitempty"`

	// (Boolean) Turn spanning tree protocol on or off. (Default: False).
	// Turn spanning tree protocol on or off. (Default: False).
	// +kubebuilder:validation:Optional
	BridgeStp *bool `json:"bridgeStp,omitempty" tf:"bridge_stp,omitempty"`

	// (String) The type of bridge to create. Possible values are: standard, ovs.
	// The type of bridge to create. Possible values are: “standard“, “ovs“.
	// +kubebuilder:validation:Optional
	BridgeType *string `json:"bridgeType,omitempty" tf:"bridge_type,omitempty"`

	// (String) The bridge interface MAC address.
	// The bridge interface MAC address.
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the bridge interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the bridge interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/machine/v1alpha1.Machine
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.Reference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.Selector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the bridge interface.
	// The MTU of the bridge interface.
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) The bridge interface name.
	// The bridge interface name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent interface name for this bridge interface.
	// Parent interface name for this bridge interface.
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (Set of String) A set of tag names to be assigned to the bridge interface.
	// A set of tag names to be assigned to the bridge interface.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the bridge interface is connected to.
	// Database ID of the VLAN the bridge interface is connected to.
	// +kubebuilder:validation:Optional
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

// InterfaceBridgeSpec defines the desired state of InterfaceBridge
type InterfaceBridgeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InterfaceBridgeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InterfaceBridgeInitParameters `json:"initProvider,omitempty"`
}

// InterfaceBridgeStatus defines the observed state of InterfaceBridge.
type InterfaceBridgeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InterfaceBridgeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InterfaceBridge is the Schema for the InterfaceBridges API. Provides a resource to manage MAAS network Bridges.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,maas}
type InterfaceBridge struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InterfaceBridgeSpec   `json:"spec"`
	Status            InterfaceBridgeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceBridgeList contains a list of InterfaceBridges
type InterfaceBridgeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfaceBridge `json:"items"`
}

// Repository type metadata.
var (
	InterfaceBridge_Kind             = "InterfaceBridge"
	InterfaceBridge_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfaceBridge_Kind}.String()
	InterfaceBridge_KindAPIVersion   = InterfaceBridge_Kind + "." + CRDGroupVersion.String()
	InterfaceBridge_GroupVersionKind = CRDGroupVersion.WithKind(InterfaceBridge_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfaceBridge{}, &InterfaceBridgeList{})
}
