// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type InterfaceVLANInitParameters struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (String) The identifier (name or ID) of the fabric for the new VLAN interface.
	// The identifier (name or ID) of the fabric for the new VLAN interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/network/v1alpha1.Fabric
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// Reference to a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricRef *v1.Reference `json:"fabricRef,omitempty" tf:"-"`

	// Selector for a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricSelector *v1.Selector `json:"fabricSelector,omitempty" tf:"-"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the VLAN interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the VLAN interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/machine/v1alpha1.Machine
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.Reference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.Selector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the VLAN interface.
	// The MTU of the VLAN interface.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// The name of the VLAN interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent interface name for this VLAN interface.
	// Parent interface name for this VLAN interface.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (Set of String) A set of tag names to be assigned to the VLAN interface.
	// A set of tag names to be assigned to the VLAN interface.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the VLAN interface is connected to.
	// Database ID of the VLAN the VLAN interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfaceVLANObservation struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (String) The identifier (name or ID) of the fabric for the new VLAN interface.
	// The identifier (name or ID) of the fabric for the new VLAN interface.
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the VLAN interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the VLAN interface.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (Number) The MTU of the VLAN interface.
	// The MTU of the VLAN interface.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// The name of the VLAN interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent interface name for this VLAN interface.
	// Parent interface name for this VLAN interface.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (Set of String) A set of tag names to be assigned to the VLAN interface.
	// A set of tag names to be assigned to the VLAN interface.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the VLAN interface is connected to.
	// Database ID of the VLAN the VLAN interface is connected to.
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

type InterfaceVLANParameters struct {

	// (Boolean) Accept router advertisements. (IPv6 only).
	// Accept router advertisements. (IPv6 only).
	// +kubebuilder:validation:Optional
	AcceptRa *bool `json:"acceptRa,omitempty" tf:"accept_ra,omitempty"`

	// (String) The identifier (name or ID) of the fabric for the new VLAN interface.
	// The identifier (name or ID) of the fabric for the new VLAN interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/network/v1alpha1.Fabric
	// +kubebuilder:validation:Optional
	Fabric *string `json:"fabric,omitempty" tf:"fabric,omitempty"`

	// Reference to a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricRef *v1.Reference `json:"fabricRef,omitempty" tf:"-"`

	// Selector for a Fabric in network to populate fabric.
	// +kubebuilder:validation:Optional
	FabricSelector *v1.Selector `json:"fabricSelector,omitempty" tf:"-"`

	// (String) The identifier (system ID, hostname, or FQDN) of the machine with the VLAN interface.
	// The identifier (system ID, hostname, or FQDN) of the machine with the VLAN interface.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/machine/v1alpha1.Machine
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.Reference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.Selector `json:"machineSelector,omitempty" tf:"-"`

	// (Number) The MTU of the VLAN interface.
	// The MTU of the VLAN interface.
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// The name of the VLAN interface.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent interface name for this VLAN interface.
	// Parent interface name for this VLAN interface.
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (Set of String) A set of tag names to be assigned to the VLAN interface.
	// A set of tag names to be assigned to the VLAN interface.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Number) Database ID of the VLAN the VLAN interface is connected to.
	// Database ID of the VLAN the VLAN interface is connected to.
	// +kubebuilder:validation:Optional
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`
}

// InterfaceVLANSpec defines the desired state of InterfaceVLAN
type InterfaceVLANSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InterfaceVLANParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InterfaceVLANInitParameters `json:"initProvider,omitempty"`
}

// InterfaceVLANStatus defines the observed state of InterfaceVLAN.
type InterfaceVLANStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InterfaceVLANObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InterfaceVLAN is the Schema for the InterfaceVLANs API. Provides a resource to manage MAAS network Vlans.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,maas}
type InterfaceVLAN struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parent) || (has(self.initProvider) && has(self.initProvider.parent))",message="spec.forProvider.parent is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vlan) || (has(self.initProvider) && has(self.initProvider.vlan))",message="spec.forProvider.vlan is a required parameter"
	Spec   InterfaceVLANSpec   `json:"spec"`
	Status InterfaceVLANStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceVLANList contains a list of InterfaceVLANs
type InterfaceVLANList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfaceVLAN `json:"items"`
}

// Repository type metadata.
var (
	InterfaceVLAN_Kind             = "InterfaceVLAN"
	InterfaceVLAN_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfaceVLAN_Kind}.String()
	InterfaceVLAN_KindAPIVersion   = InterfaceVLAN_Kind + "." + CRDGroupVersion.String()
	InterfaceVLAN_GroupVersionKind = CRDGroupVersion.WithKind(InterfaceVLAN_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfaceVLAN{}, &InterfaceVLANList{})
}
