// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SubnetIPRangeInitParameters struct {

	// (String) A description of this range. This argument is computed if it's not set.
	// A description of this range. This argument is computed if it's not set.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The end IP for the new IP range (inclusive).
	// The end IP for the new IP range (inclusive).
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (String) The start IP for the new IP range (inclusive).
	// The start IP for the new IP range (inclusive).
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) The subnet identifier (ID or CIDR) for the new IP range.
	// The subnet identifier (ID or CIDR) for the new IP range.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/network/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("cidr", true)
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// Reference to a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetRef *v1.Reference `json:"subnetRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetSelector *v1.Selector `json:"subnetSelector,omitempty" tf:"-"`

	// (String) The IP range type. Valid options are: dynamic, reserved.
	// The IP range type. Valid options are: `dynamic`, `reserved`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SubnetIPRangeObservation struct {

	// (String) A description of this range. This argument is computed if it's not set.
	// A description of this range. This argument is computed if it's not set.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The end IP for the new IP range (inclusive).
	// The end IP for the new IP range (inclusive).
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The start IP for the new IP range (inclusive).
	// The start IP for the new IP range (inclusive).
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) The subnet identifier (ID or CIDR) for the new IP range.
	// The subnet identifier (ID or CIDR) for the new IP range.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// (String) The IP range type. Valid options are: dynamic, reserved.
	// The IP range type. Valid options are: `dynamic`, `reserved`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SubnetIPRangeParameters struct {

	// (String) A description of this range. This argument is computed if it's not set.
	// A description of this range. This argument is computed if it's not set.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The end IP for the new IP range (inclusive).
	// The end IP for the new IP range (inclusive).
	// +kubebuilder:validation:Optional
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (String) The start IP for the new IP range (inclusive).
	// The start IP for the new IP range (inclusive).
	// +kubebuilder:validation:Optional
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) The subnet identifier (ID or CIDR) for the new IP range.
	// The subnet identifier (ID or CIDR) for the new IP range.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/cluster/network/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("cidr", true)
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// Reference to a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetRef *v1.Reference `json:"subnetRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnet.
	// +kubebuilder:validation:Optional
	SubnetSelector *v1.Selector `json:"subnetSelector,omitempty" tf:"-"`

	// (String) The IP range type. Valid options are: dynamic, reserved.
	// The IP range type. Valid options are: `dynamic`, `reserved`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// SubnetIPRangeSpec defines the desired state of SubnetIPRange
type SubnetIPRangeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SubnetIPRangeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetIPRangeInitParameters `json:"initProvider,omitempty"`
}

// SubnetIPRangeStatus defines the observed state of SubnetIPRange.
type SubnetIPRangeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetIPRangeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SubnetIPRange is the Schema for the SubnetIPRanges API. Provides a resource to manage MAAS network subnets IP ranges.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,maas}
type SubnetIPRange struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endIp) || (has(self.initProvider) && has(self.initProvider.endIp))",message="spec.forProvider.endIp is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startIp) || (has(self.initProvider) && has(self.initProvider.startIp))",message="spec.forProvider.startIp is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   SubnetIPRangeSpec   `json:"spec"`
	Status SubnetIPRangeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetIPRangeList contains a list of SubnetIPRanges
type SubnetIPRangeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SubnetIPRange `json:"items"`
}

// Repository type metadata.
var (
	SubnetIPRange_Kind             = "SubnetIPRange"
	SubnetIPRange_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SubnetIPRange_Kind}.String()
	SubnetIPRange_KindAPIVersion   = SubnetIPRange_Kind + "." + CRDGroupVersion.String()
	SubnetIPRange_GroupVersionKind = CRDGroupVersion.WithKind(SubnetIPRange_Kind)
)

func init() {
	SchemeBuilder.Register(&SubnetIPRange{}, &SubnetIPRangeList{})
}
