// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BlockDeviceInitParameters struct {

	// (Number) The block size of the block device. Defaults to 512.
	// The block size of the block device. Defaults to `512`.
	BlockSize *float64 `json:"blockSize,omitempty" tf:"block_size,omitempty"`

	// (String) Only used if model and serial cannot be provided. This should be a path that is fixed and doesn't change depending on the boot order or kernel version. This argument is computed if it's not given.
	// Only used if `model` and `serial` cannot be provided. This should be a path that is fixed and doesn't change depending on the boot order or kernel version. This argument is computed if it's not given.
	IDPath *string `json:"idPath,omitempty" tf:"id_path,omitempty"`

	// (Boolean) Boolean value indicating if the block device is set as the boot device.
	// Boolean value indicating if the block device is set as the boot device.
	IsBootDevice *bool `json:"isBootDevice,omitempty" tf:"is_boot_device,omitempty"`

	// (String) The machine identifier (system ID, hostname, or FQDN) that owns the block device.
	// The machine identifier (system ID, hostname, or FQDN) that owns the block device.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (String) Model of the block device. Used in conjunction with serial argument. Conflicts with id_path. This argument is computed if it's not given.
	// Model of the block device. Used in conjunction with `serial` argument. Conflicts with `id_path`. This argument is computed if it's not given.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String) The block device name.
	// The block device name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// as-blocks mode. And, it is computed if it's not given. (see below for nested schema)
	// List of partition resources created for the new block device. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html). And, it is computed if it's not given.
	Partitions []PartitionsInitParameters `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// (String) Serial number of the block device. Used in conjunction with model argument. Conflicts with id_path. This argument is computed if it's not given.
	// Serial number of the block device. Used in conjunction with `model` argument. Conflicts with `id_path`. This argument is computed if it's not given.
	Serial *string `json:"serial,omitempty" tf:"serial,omitempty"`

	// (Number) The size of the block device (given in GB).
	// The size of the block device (given in GB).
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`

	// (Set of String) A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type BlockDeviceObservation struct {

	// (Number) The block size of the block device. Defaults to 512.
	// The block size of the block device. Defaults to `512`.
	BlockSize *float64 `json:"blockSize,omitempty" tf:"block_size,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Only used if model and serial cannot be provided. This should be a path that is fixed and doesn't change depending on the boot order or kernel version. This argument is computed if it's not given.
	// Only used if `model` and `serial` cannot be provided. This should be a path that is fixed and doesn't change depending on the boot order or kernel version. This argument is computed if it's not given.
	IDPath *string `json:"idPath,omitempty" tf:"id_path,omitempty"`

	// (Boolean) Boolean value indicating if the block device is set as the boot device.
	// Boolean value indicating if the block device is set as the boot device.
	IsBootDevice *bool `json:"isBootDevice,omitempty" tf:"is_boot_device,omitempty"`

	// (String) The machine identifier (system ID, hostname, or FQDN) that owns the block device.
	// The machine identifier (system ID, hostname, or FQDN) that owns the block device.
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// (String) Model of the block device. Used in conjunction with serial argument. Conflicts with id_path. This argument is computed if it's not given.
	// Model of the block device. Used in conjunction with `serial` argument. Conflicts with `id_path`. This argument is computed if it's not given.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String) The block device name.
	// The block device name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// as-blocks mode. And, it is computed if it's not given. (see below for nested schema)
	// List of partition resources created for the new block device. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html). And, it is computed if it's not given.
	Partitions []PartitionsObservation `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// (String) Block device path.
	// Block device path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) Serial number of the block device. Used in conjunction with model argument. Conflicts with id_path. This argument is computed if it's not given.
	// Serial number of the block device. Used in conjunction with `model` argument. Conflicts with `id_path`. This argument is computed if it's not given.
	Serial *string `json:"serial,omitempty" tf:"serial,omitempty"`

	// (Number) The size of the block device (given in GB).
	// The size of the block device (given in GB).
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`

	// (Set of String) A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Block device UUID.
	// Block device UUID.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type BlockDeviceParameters struct {

	// (Number) The block size of the block device. Defaults to 512.
	// The block size of the block device. Defaults to `512`.
	// +kubebuilder:validation:Optional
	BlockSize *float64 `json:"blockSize,omitempty" tf:"block_size,omitempty"`

	// (String) Only used if model and serial cannot be provided. This should be a path that is fixed and doesn't change depending on the boot order or kernel version. This argument is computed if it's not given.
	// Only used if `model` and `serial` cannot be provided. This should be a path that is fixed and doesn't change depending on the boot order or kernel version. This argument is computed if it's not given.
	// +kubebuilder:validation:Optional
	IDPath *string `json:"idPath,omitempty" tf:"id_path,omitempty"`

	// (Boolean) Boolean value indicating if the block device is set as the boot device.
	// Boolean value indicating if the block device is set as the boot device.
	// +kubebuilder:validation:Optional
	IsBootDevice *bool `json:"isBootDevice,omitempty" tf:"is_boot_device,omitempty"`

	// (String) The machine identifier (system ID, hostname, or FQDN) that owns the block device.
	// The machine identifier (system ID, hostname, or FQDN) that owns the block device.
	// +crossplane:generate:reference:type=github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1.Machine
	// +kubebuilder:validation:Optional
	Machine *string `json:"machine,omitempty" tf:"machine,omitempty"`

	// Reference to a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineRef *v1.NamespacedReference `json:"machineRef,omitempty" tf:"-"`

	// Selector for a Machine in machine to populate machine.
	// +kubebuilder:validation:Optional
	MachineSelector *v1.NamespacedSelector `json:"machineSelector,omitempty" tf:"-"`

	// (String) Model of the block device. Used in conjunction with serial argument. Conflicts with id_path. This argument is computed if it's not given.
	// Model of the block device. Used in conjunction with `serial` argument. Conflicts with `id_path`. This argument is computed if it's not given.
	// +kubebuilder:validation:Optional
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String) The block device name.
	// The block device name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// as-blocks mode. And, it is computed if it's not given. (see below for nested schema)
	// List of partition resources created for the new block device. Parameters defined below. This argument is processed in [attribute-as-blocks mode](https://www.io/docs/configuration/attr-as-blocks.html). And, it is computed if it's not given.
	// +kubebuilder:validation:Optional
	Partitions []PartitionsParameters `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// (String) Serial number of the block device. Used in conjunction with model argument. Conflicts with id_path. This argument is computed if it's not given.
	// Serial number of the block device. Used in conjunction with `model` argument. Conflicts with `id_path`. This argument is computed if it's not given.
	// +kubebuilder:validation:Optional
	Serial *string `json:"serial,omitempty" tf:"serial,omitempty"`

	// (Number) The size of the block device (given in GB).
	// The size of the block device (given in GB).
	// +kubebuilder:validation:Optional
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`

	// (Set of String) A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type PartitionsInitParameters struct {

	// (Boolean) Boolean value indicating if the partition is set as bootable.
	// Boolean value indicating if the partition is set as bootable.
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) The file system type (e.g. ext4). If this is not set, the partition is unformatted.
	// The file system type (e.g. `ext4`). If this is not set, the partition is unformatted.
	FsType *string `json:"fsType,omitempty" tf:"fs_type,omitempty"`

	// (String) The label assigned if the partition is formatted.
	// The label assigned if the partition is formatted.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) The options used for the partition mount.
	// The options used for the partition mount.
	MountOptions *string `json:"mountOptions,omitempty" tf:"mount_options,omitempty"`

	// (String) The mount point used. If this is not set, the partition is not mounted. This is used only the partition is formatted.
	// The mount point used. If this is not set, the partition is not mounted. This is used only the partition is formatted.
	MountPoint *string `json:"mountPoint,omitempty" tf:"mount_point,omitempty"`

	// (Number) The size of the block device (given in GB).
	// The partition size (given in GB).
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`

	// (Set of String) A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// The tags assigned to the new block device partition.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type PartitionsObservation struct {

	// (Boolean) Boolean value indicating if the partition is set as bootable.
	// Boolean value indicating if the partition is set as bootable.
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) The file system type (e.g. ext4). If this is not set, the partition is unformatted.
	// The file system type (e.g. `ext4`). If this is not set, the partition is unformatted.
	FsType *string `json:"fsType,omitempty" tf:"fs_type,omitempty"`

	// (String) The ID of this resource.
	// The ID of the partition.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The label assigned if the partition is formatted.
	// The label assigned if the partition is formatted.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) The options used for the partition mount.
	// The options used for the partition mount.
	MountOptions *string `json:"mountOptions,omitempty" tf:"mount_options,omitempty"`

	// (String) The mount point used. If this is not set, the partition is not mounted. This is used only the partition is formatted.
	// The mount point used. If this is not set, the partition is not mounted. This is used only the partition is formatted.
	MountPoint *string `json:"mountPoint,omitempty" tf:"mount_point,omitempty"`

	// (String) Block device path.
	// The path of the partition.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) The size of the block device (given in GB).
	// The partition size (given in GB).
	SizeGigabytes *float64 `json:"sizeGigabytes,omitempty" tf:"size_gigabytes,omitempty"`

	// (Set of String) A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// The tags assigned to the new block device partition.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type PartitionsParameters struct {

	// (Boolean) Boolean value indicating if the partition is set as bootable.
	// Boolean value indicating if the partition is set as bootable.
	// +kubebuilder:validation:Optional
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) The file system type (e.g. ext4). If this is not set, the partition is unformatted.
	// The file system type (e.g. `ext4`). If this is not set, the partition is unformatted.
	// +kubebuilder:validation:Optional
	FsType *string `json:"fsType,omitempty" tf:"fs_type,omitempty"`

	// (String) The label assigned if the partition is formatted.
	// The label assigned if the partition is formatted.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) The options used for the partition mount.
	// The options used for the partition mount.
	// +kubebuilder:validation:Optional
	MountOptions *string `json:"mountOptions,omitempty" tf:"mount_options,omitempty"`

	// (String) The mount point used. If this is not set, the partition is not mounted. This is used only the partition is formatted.
	// The mount point used. If this is not set, the partition is not mounted. This is used only the partition is formatted.
	// +kubebuilder:validation:Optional
	MountPoint *string `json:"mountPoint,omitempty" tf:"mount_point,omitempty"`

	// (Number) The size of the block device (given in GB).
	// The partition size (given in GB).
	// +kubebuilder:validation:Optional
	SizeGigabytes *float64 `json:"sizeGigabytes" tf:"size_gigabytes,omitempty"`

	// (Set of String) A set of tag names assigned to the new block device. This argument is computed if it's not given.
	// The tags assigned to the new block device partition.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// BlockDeviceSpec defines the desired state of BlockDevice
type BlockDeviceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BlockDeviceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BlockDeviceInitParameters `json:"initProvider,omitempty"`
}

// BlockDeviceStatus defines the observed state of BlockDevice.
type BlockDeviceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BlockDeviceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BlockDevice is the Schema for the BlockDevices API. Provides a resource to manage MAAS machines' block devices.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,maas}
type BlockDevice struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sizeGigabytes) || (has(self.initProvider) && has(self.initProvider.sizeGigabytes))",message="spec.forProvider.sizeGigabytes is a required parameter"
	Spec   BlockDeviceSpec   `json:"spec"`
	Status BlockDeviceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BlockDeviceList contains a list of BlockDevices
type BlockDeviceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BlockDevice `json:"items"`
}

// Repository type metadata.
var (
	BlockDevice_Kind             = "BlockDevice"
	BlockDevice_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BlockDevice_Kind}.String()
	BlockDevice_KindAPIVersion   = BlockDevice_Kind + "." + CRDGroupVersion.String()
	BlockDevice_GroupVersionKind = CRDGroupVersion.WithKind(BlockDevice_Kind)
)

func init() {
	SchemeBuilder.Register(&BlockDevice{}, &BlockDeviceList{})
}
