// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/Marouan-chak/provider-upjet-maas/apis/namespaced/machine/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this BlockDevice.
func (mg *BlockDevice) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MachineRef,
		Selector:     mg.Spec.ForProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Machine")
	}
	mg.Spec.ForProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MachineRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Machine),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MachineRef,
		Selector:     mg.Spec.InitProvider.MachineSelector,
		To: reference.To{
			List:    &v1alpha1.MachineList{},
			Managed: &v1alpha1.Machine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Machine")
	}
	mg.Spec.InitProvider.Machine = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MachineRef = rsp.ResolvedReference

	return nil
}
