---
# OPTIONAL: Assign a static IP to a machine's interface
# Only use after machine is commissioned in MAAS
apiVersion: network.maas.crossplane.io/v1alpha1
kind: InterfaceLink
metadata:
  name: proxmox-vm-static-ip
spec:
  forProvider:
    # Reference to the machine (must exist and be commissioned)
    machineRef:
      name: proxmox-vm
    # Network interface name on the machine
    networkInterface: eth0
    # Reference to the provisioning subnet
    subnetRef:
      name: provisioning-subnet
    # Link mode: AUTO, DHCP, STATIC, or LINK_UP
    mode: STATIC
    # Static IP from the provisioning subnet
    ipAddress: "192.168.50.50"
    # Set as default gateway
    defaultGateway: true
  providerConfigRef:
    name: default
