---
# OPTIONAL: Create a VLAN interface on a machine
# Only needed if using VLAN tagging on the machine
apiVersion: network.maas.crossplane.io/v1alpha1
kind: InterfaceVLAN
metadata:
  name: proxmox-vm-vlan-if
spec:
  forProvider:
    # Reference to the machine (must exist and be commissioned)
    machineRef:
      name: proxmox-vm
    # Reference to the fabric
    fabricRef:
      name: provisioning-fabric
    # Parent interface
    parent: eth0
    # VLAN ID
    vlan: 50
  providerConfigRef:
    name: default
