---
# OPTIONAL: Create a network bond on a machine
# Requires machine with multiple NICs - not typical for simple Proxmox VM
apiVersion: network.maas.crossplane.io/v1alpha1
kind: InterfaceBond
metadata:
  name: proxmox-vm-bond
spec:
  forProvider:
    # Reference to the machine (must exist and be commissioned)
    machineRef:
      name: proxmox-vm
    # Bond configuration
    name: bond0
    # Parent interfaces (physical NICs to bond)
    parents:
      - eth0
      - eth1
    # Bond mode: balance-rr, active-backup, balance-xor, broadcast, 802.3ad, balance-tlb, balance-alb
    bondMode: "802.3ad"
    bondMiimon: 100
    bondLacpRate: fast
    mtu: 1500
  providerConfigRef:
    name: default
