---
# Additional IP range on an existing subnet
# Use this to add more IP ranges after subnet creation
apiVersion: network.maas.crossplane.io/v1alpha1
kind: SubnetIPRange
metadata:
  name: my-reserved-range
spec:
  forProvider:
    # Reference to the subnet
    subnetRef:
      name: my-subnet
    # Range type: 'reserved' or 'dynamic'
    type: reserved
    startIp: "10.0.0.240"
    endIp: "10.0.0.250"
    comment: "Reserved for static assignments"
  providerConfigRef:
    name: default
